const fs = require('fs');
const path = require('path');

const dbPath = path.join(__dirname, '..', 'data', 'webstudioae.db.json');
const raw = fs.readFileSync(dbPath, 'utf8');
const data = JSON.parse(raw);

const verifiedPrices = [
  {
    id: 'tomato-fresh',
    name: 'Fresh Red Tomato',
    unit: 'CTN',
    pkg: 'Carton 6 KG',
    weight: 6,
    containerPrice: 18.00,
    marketPrice: 22.00,
    prevMarketPrice: 24.00,
    trend: 'DOWN',
    moq: '1 x 40ft Reefer Container (2,400 CTN)',
    minQty: '25 Cartons',
  },
  {
    id: 'potato-yellow',
    name: 'Fresh Yellow Potato',
    unit: 'BAG',
    pkg: 'Mesh Bag 10 KG',
    weight: 10,
    containerPrice: 24.00,
    marketPrice: 28.00,
    prevMarketPrice: 28.00,
    trend: 'STABLE',
    moq: '1 x 40ft Reefer Container (2,600 Bags)',
    minQty: '50 Bags',
  },
  {
    id: 'onion-red',
    name: 'Fresh Red & White Onion',
    unit: 'BAG',
    pkg: 'Mesh Bag 10 KG',
    weight: 10,
    containerPrice: 22.00,
    marketPrice: 26.50,
    prevMarketPrice: 25.00,
    trend: 'UP',
    moq: '1 x 40ft Container (2,800 Bags)',
    minQty: '50 Bags',
  },
  {
    id: 'carrot-orange',
    name: 'Fresh Orange Carrot',
    unit: 'CTN',
    pkg: 'Carton 10 KG',
    weight: 10,
    containerPrice: 32.00,
    marketPrice: 38.00,
    prevMarketPrice: 36.00,
    trend: 'UP',
    moq: '1 x 40ft Reefer Container (2,200 CTN)',
    minQty: '30 Cartons',
  },
  {
    id: 'cucumber-green',
    name: 'Farm Fresh Green Cucumber',
    unit: 'BOX',
    pkg: 'Box 5 KG',
    weight: 5,
    containerPrice: 14.00,
    marketPrice: 18.00,
    prevMarketPrice: 17.00,
    trend: 'UP',
    moq: '1 x 40ft Reefer (3,000 Boxes)',
    minQty: '20 Boxes',
  },
  {
    id: 'capsicum-mixed',
    name: 'Green & Colored Capsicum',
    unit: 'CTN',
    pkg: 'Carton 5 KG',
    weight: 5,
    containerPrice: 22.00,
    marketPrice: 27.50,
    prevMarketPrice: 29.00,
    trend: 'DOWN',
    moq: '1 x 40ft Reefer (2,500 CTN)',
    minQty: '20 Cartons',
  },
  {
    id: 'lemon-yellow',
    name: 'Fresh Yellow Lemon',
    unit: 'CTN',
    pkg: 'Carton 15 KG',
    weight: 15,
    containerPrice: 44.00,
    marketPrice: 52.00,
    prevMarketPrice: 50.00,
    trend: 'UP',
    moq: '1 x 40ft Reefer Container (1,600 CTN)',
    minQty: '25 Cartons',
  },
  {
    id: 'orange-valencia',
    name: 'Valencia Sweet Orange',
    unit: 'CTN',
    pkg: 'Carton 15 KG',
    weight: 15,
    containerPrice: 42.00,
    marketPrice: 48.00,
    prevMarketPrice: 46.00,
    trend: 'UP',
    moq: '1 x 40ft Reefer Container (1,600 CTN)',
    minQty: '30 Cartons',
  },
  {
    id: 'apple-fuji',
    name: 'Crisp Fuji & Gala Apple',
    unit: 'CTN',
    pkg: 'Carton 18 KG',
    weight: 18,
    containerPrice: 65.00,
    marketPrice: 75.00,
    prevMarketPrice: 78.00,
    trend: 'DOWN',
    moq: '1 x 40ft Reefer Container (1,200 CTN)',
    minQty: '20 Cartons',
  },
  {
    id: 'banana-cavendish',
    name: 'Cavendish Green & Yellow Banana',
    unit: 'CTN',
    pkg: 'Carton 13 KG',
    weight: 13,
    containerPrice: 48.00,
    marketPrice: 55.00,
    prevMarketPrice: 55.00,
    trend: 'STABLE',
    moq: '1 x 40ft Controlled Atmosphere Reefer (1,540 CTN)',
    minQty: '50 Cartons',
  },
  {
    id: 'garlic-white',
    name: 'Fresh White Garlic',
    unit: 'CTN',
    pkg: 'Carton 10 KG',
    weight: 10,
    containerPrice: 45.00,
    marketPrice: 54.00,
    prevMarketPrice: 58.00,
    trend: 'DOWN',
    moq: '1 x 40ft Container (2,500 CTN)',
    minQty: '20 Cartons',
  },
  {
    id: 'ginger-fresh',
    name: 'Fresh Chinese & Indian Ginger',
    unit: 'CTN',
    pkg: 'Carton 5 KG',
    weight: 5,
    containerPrice: 28.00,
    marketPrice: 35.00,
    prevMarketPrice: 35.00,
    trend: 'STABLE',
    moq: '1 x 40ft Container (3,000 CTN)',
    minQty: '20 Cartons',
  },
  {
    id: 'chilli-green',
    name: 'Fresh Green Chilli',
    unit: 'BOX',
    pkg: 'Box 3 KG',
    weight: 3,
    containerPrice: 16.00,
    marketPrice: 21.00,
    prevMarketPrice: 20.00,
    trend: 'UP',
    moq: 'Air Freight Pallet (500 Boxes) / Reefer',
    minQty: '15 Boxes',
  },
  {
    id: 'cauliflower-fresh',
    name: 'Fresh White Cauliflower',
    unit: 'CTN',
    pkg: 'Carton 8 KG',
    weight: 8,
    containerPrice: 25.00,
    marketPrice: 32.00,
    prevMarketPrice: 30.00,
    trend: 'UP',
    moq: '1 x 40ft Reefer (2,000 CTN)',
    minQty: '25 Cartons',
  },
  {
    id: 'cabbage-green',
    name: 'Fresh Green Drumhead Cabbage',
    unit: 'BAG',
    pkg: 'Mesh Bag 15 KG',
    weight: 15,
    containerPrice: 22.00,
    marketPrice: 28.00,
    prevMarketPrice: 28.00,
    trend: 'STABLE',
    moq: '1 x 40ft Reefer (1,800 Bags)',
    minQty: '30 Bags',
  },
  {
    id: 'eggplant-purple',
    name: 'Fresh Purple Eggplant',
    unit: 'BOX',
    pkg: 'Box 6 KG',
    weight: 6,
    containerPrice: 18.00,
    marketPrice: 23.50,
    prevMarketPrice: 22.00,
    trend: 'UP',
    moq: '1 x 40ft Reefer (2,200 Boxes)',
    minQty: '25 Boxes',
  },
  {
    id: 'lentils-yellow-red',
    name: 'Yellow & Red Football Lentils',
    unit: 'BAG',
    pkg: 'Bag 25 KG',
    weight: 25,
    containerPrice: 95.00,
    marketPrice: 110.00,
    prevMarketPrice: 115.00,
    trend: 'DOWN',
    moq: '1 x 20ft Container (960 Bags / 24 MT)',
    minQty: '15 Bags',
  },
  {
    id: 'chickpeas-kabuli',
    name: 'Whole Kabuli Chickpeas (8mm/9mm)',
    unit: 'BAG',
    pkg: 'Bag 25 KG',
    weight: 25,
    containerPrice: 118.00,
    marketPrice: 135.00,
    prevMarketPrice: 135.00,
    trend: 'STABLE',
    moq: '1 x 20ft Container (960 Bags / 24 MT)',
    minQty: '15 Bags',
  },
  {
    id: 'rice-basmati-1121',
    name: 'XL 1121 Steam Basmati Rice',
    unit: 'BAG',
    pkg: 'Bag 40 KG',
    weight: 40,
    containerPrice: 165.00,
    marketPrice: 190.00,
    prevMarketPrice: 185.00,
    trend: 'UP',
    moq: '1 x 20ft Heavy Container (600 Bags / 24 MT)',
    minQty: '10 Bags',
  },
  {
    id: 'spices-red-chilli-whole',
    name: 'Whole Red Chilli & Spices',
    unit: 'BAG',
    pkg: 'Bag 25 KG',
    weight: 25,
    containerPrice: 210.00,
    marketPrice: 245.00,
    prevMarketPrice: 240.00,
    trend: 'UP',
    moq: '1 x 20ft Container (600 Bags / 15 MT)',
    minQty: '10 Bags',
  },
  {
    id: 'spices-black-pepper',
    name: 'Whole Malabar Black Pepper',
    unit: 'BAG',
    pkg: 'Bag 25 KG',
    weight: 25,
    containerPrice: 420.00,
    marketPrice: 480.00,
    prevMarketPrice: 470.00,
    trend: 'UP',
    moq: '1 x 20ft Container (480 Bags / 12 MT)',
    minQty: '5 Bags',
  },
  {
    id: 'dry-nuts-cashew-almond',
    name: 'Whole Cashews & Almonds',
    unit: 'CTN',
    pkg: 'Carton 10 KG',
    weight: 10,
    containerPrice: 340.00,
    marketPrice: 390.00,
    prevMarketPrice: 385.00,
    trend: 'UP',
    moq: '1 x 20ft Container (1,000 CTN / 10 MT)',
    minQty: '5 Cartons',
  },
];

const nowISO = new Date().toISOString();

data.foodstuffContainerPrices = verifiedPrices.map((item) => ({
  id: `cp-${item.id}`,
  productId: item.id,
  importerSupplierName: 'Barakah Global Importers Stream',
  packagingUnit: item.unit,
  packagingDetails: item.pkg,
  netWeightKg: item.weight,
  priceAED: item.containerPrice,
  calculatedPricePerKg: item.weight ? parseFloat((item.containerPrice / item.weight).toFixed(2)) : null,
  moq: item.moq,
  containerAvailability: 'Direct Port Allocation (Jebel Ali / Dubai Ports)',
  portOfArrival: 'Jebel Ali Port / Dubai Ports',
  businessStatus: 'AVAILABLE',
  lastUpdated: nowISO,
  updateSession: 'MIDDAY',
  updateSource: 'AUTHORIZED_CLIENT_ENTRY',
  updatedBy: 'admin@webstudioae.com',
  quotationNotes: 'Official Barakah Al Rizq import quotation rate. Valid for full container booking.',
}));

data.foodstuffMarketPrices = verifiedPrices.map((item) => {
  const diff = item.prevMarketPrice ? item.marketPrice - item.prevMarketPrice : 0;
  const pct = item.prevMarketPrice ? parseFloat(((diff / item.prevMarketPrice) * 100).toFixed(2)) : 0;
  return {
    id: `mp-${item.id}`,
    productId: item.id,
    marketLocation: 'Al Aweer Central Fruit & Vegetable Market, Ras Al Khor, Dubai',
    packagingUnit: item.unit,
    packagingDetails: item.pkg,
    netWeightKg: item.weight,
    priceAED: item.marketPrice,
    previousPriceAED: item.prevMarketPrice,
    changePercent: pct,
    trend: item.trend,
    calculatedPricePerKg: item.weight ? parseFloat((item.marketPrice / item.weight).toFixed(2)) : null,
    minPurchaseQty: item.minQty,
    qualityGrade: 'Grade A Market Fresh',
    marketSession: 'MIDDAY',
    businessStatus: 'AVAILABLE',
    lastUpdated: nowISO,
    updateSource: 'AUTHORIZED_CLIENT_ENTRY',
    updatedBy: 'admin@webstudioae.com',
  };
});

fs.writeFileSync(dbPath, JSON.stringify(data, null, 2), 'utf8');
console.log('Successfully updated 22 container prices and 22 market prices with exact matching product IDs!');
