const fs = require('fs');
const path = require('path');

const targetPath = path.join(__dirname, '..', 'src', 'data', 'vantageCatalogData.ts');

const waterfront = [
  ["VANTAGE HORIZON TOWER", "Dubai Marina Waterfront", "Dubai", "Off-Plan", "Apartments", 1850000, "Q4 2028", "Studio, 1BR, 2BR & 3BR Sky Residences", "60/40 Construction Linked", 18, 8.4, ["Infinity Sky Pool", "Private Yacht Berth Access", "Hydrotherapy Spa", "24/7 Valet & Executive Concierge"], "DLD Escrow #99214 / FAB Bank", true],
  ["AZURE BAY RESIDENCES", "Palm Jumeirah East Crescent", "Dubai", "Under Construction", "Apartments", 4200000, "Q2 2027", "2BR, 3BR & 4BR Beachfront Suites", "70/30 on Handover", 42, 7.8, ["Private Beach Club", "Infinity Edge Lagoon", "Smart Home Automation", "Michelin Chef Private Dining"], "DLD Escrow #88142 / Emirates NBD", true],
  ["CANAL CROWN MARINA RESIDENCES", "Dubai Water Canal, Business Bay", "Dubai", "Off-Plan", "Apartments", 2400000, "Q1 2029", "1BR, 2BR & 3BR Canal Residences", "60/40 Post-Handover Option", 12, 8.9, ["Canal Boardwalk Access", "Rooftop Observatory Deck", "Technogym Wellness Hub", "Water Taxi Station Tie-In"], "DLD Escrow #91024 / ADCB", true],
  ["CREEK COVE PANORAMA", "Dubai Creek Harbour", "Dubai", "Under Construction", "Apartments", 1950000, "Q3 2027", "1BR, 2BR & 3BR Creek Residences", "80/20 on Handover", 58, 8.2, ["Direct Marina Promenade", "Burj Khalifa Sunset Deck", "Kids Splash Waterpark", "EV Fast Charging Bays"], "DLD Escrow #84109 / DIB", true],
  ["LA MER SEAVIEW PAVILION", "Port de La Mer, Jumeirah 1", "Dubai", "Ready", "Apartments", 3100000, "Ready for Handover", "1BR, 2BR & 3BR Riviera Suites", "100% Ready (Immediate Handover)", 100, 7.6, ["Mediterranean Marina Slipway", "Private Beach Access", "Boutique Retail Piazza", "Residents Private Lounge"], "DLD Escrow Cleared / Title Deed Ready", false],
  ["YAS COVE WATERFRONT FLATS", "Yas Bay Marina, Yas Island", "Abu Dhabi", "Off-Plan", "Apartments", 1450000, "Q4 2028", "Studio, 1BR, 2BR & 3BR Bay Suites", "60/40 (10% Down)", 15, 9.1, ["Etihad Arena Walkway", "Waterfront Infinity Lagoon", "Pet-Friendly Promenade", "Yacht Charter Booking Desk"], "AD DMT Escrow #44120 / First Abu Dhabi Bank", true],
  ["SAADIYAT MARINA GRANDEUR", "Saadiyat Marina District", "Abu Dhabi", "Under Construction", "Apartments", 2800000, "Q1 2028", "1BR, 2BR, 3BR & 4BR Marina Suites", "70/30 Construction Linked", 35, 7.9, ["Louvre Abu Dhabi Vista", "Private Marina Mooring", "Seafront Promenade Cafes", "Wellness Thermal Baths"], "AD DMT Escrow #55912 / ADIB", true],
  ["PALM JUMEIRAH ROYAL APEX", "Palm Jumeirah West Trunk", "Dubai", "Under Construction", "Apartments", 5600000, "Q3 2027", "3BR & 4BR Seafront Residences", "60/40 Milestone Linked", 64, 7.4, ["Private Palm Beach", "Lap Pool & Sun Cabanas", "Private Screening Cinema", "Chauffeur & Butler Quarters"], "DLD Escrow #82341 / Mashreq", true],
  ["DUBAI ISLANDS BREEZE RESIDENCES", "Dubai Islands Waterfront", "Dubai", "Off-Plan", "Apartments", 1650000, "Q2 2029", "1BR, 2BR & 3BR Ocean Residences", "50/50 (1% Monthly Post-Handover)", 10, 9.4, ["Blue Flag Beach Frontage", "Golf Island Promenade", "Water Sports Center", "Resort Style Lagoons"], "DLD Escrow #98124 / Commercial Bank of Dubai", true],
  ["MARITIME CITY HARBOUR TOWER", "Dubai Maritime City", "Dubai", "Off-Plan", "Apartments", 1750000, "Q4 2028", "1BR, 2BR & 3BR Coastal Suites", "60/40 Construction Linked", 16, 8.8, ["Unobstructed Arabian Gulf Views", "Infinity Horizon Pool", "Rooftop Sky Lounge", "Direct Cruise Terminal Access"], "DLD Escrow #93144 / Emirates Islamic", false],
  ["JBR BLUE WATERS VUE", "JBR Beachfront Walk", "Dubai", "Ready", "Apartments", 3800000, "Ready for Handover", "2BR & 3BR Seafront Residences", "100% Cash / Bank Mortgage", 100, 7.7, ["Ain Dubai Panoramic Views", "Private Footbridge to Bluewaters", "Direct JBR Beach Access", "Celebrity Dining Concourse"], "DLD Title Deed Ready", false],
  ["CREEK WATERS LUXE SUITES", "Dubai Creek Harbour Island", "Dubai", "Under Construction", "Apartments", 2150000, "Q1 2028", "1BR, 2BR & 3BR Urban Waterfront", "70/30 Handover Linked", 48, 8.5, ["Creek Beach Direct Access", "Infinity Sunset Lagoon", "Fully Equipped Gym & Spa", "Children Creative Play Studio"], "DLD Escrow #87652 / Emirates NBD", false],
  ["MARINA COVE HAVEN", "Dubai Marina South Gateway", "Dubai", "Off-Plan", "Apartments", 1900000, "Q3 2028", "1BR & 2BR Marina Suites", "60/40 Payment Plan", 20, 8.6, ["Marina Mall Walkway", "Panoramic Marina Sky Gym", "Sauna & Ice Bath Sanctuary", "24/7 Concierge Support"], "DLD Escrow #94512 / FAB", false],
  ["AL REEM SEABREEZE TOWER", "Marina Square, Al Reem Island", "Abu Dhabi", "Ready", "Apartments", 1200000, "Ready for Handover", "Studio, 1BR & 2BR Waterfront Units", "Ready with 3-Year Post-Handover", 100, 9.2, ["Mangrove Forest Views", "Olympic Length Swimming Pool", "Tennis & Padel Courts", "Hypermarket in Podium"], "AD DMT Certified", true],
  ["CANAL HEIGHTS WATERFALL RESIDENCE", "Business Bay Canal Promenade", "Dubai", "Under Construction", "Apartments", 2250000, "Q2 2027", "Studio, 1BR & 2BR Canal Suites", "80/20 on Completion", 55, 9.0, ["Interactive Waterfall Facade", "Yoga & Meditation Deck", "Smart Parcel Lockers", "High-Speed EV Chargers"], "DLD Escrow #86411 / ADCB", false],
  ["PALM CROWN SIGNATURE SUITES", "Palm Jumeirah Crescent Gateway", "Dubai", "Under Construction", "Apartments", 6800000, "Q4 2027", "3BR & 4BR Royal Penthouses", "60/40 Construction Linked", 50, 7.2, ["Private Plunge Pool on Balcony", "Helipad Access Protocol", "Dedicated Sommelier Cellar", "VIP Security Escort Desk"], "DLD Escrow #81099 / Emirates NBD", true],
  ["WATERFRONT PENINSULA SUITES", "Peninsula, Business Bay Canal", "Dubai", "Under Construction", "Apartments", 2600000, "Q3 2027", "1BR, 2BR & 3BR Waterfront Towers", "70/30 Handover Linked", 60, 8.4, ["360 Canal & Downtown Views", "Promenade Retail & Cafes", "Outdoor Cinema Lounge", "Squash & Basketball Courts"], "DLD Escrow #85213 / DIB", false],
  ["JUMEIRAH BAY SHORE RESIDENCES", "Jumeirah 1 Coastline", "Dubai", "Off-Plan", "Apartments", 4500000, "Q2 2029", "2BR, 3BR & 4BR Coastal Homes", "60/40 (10% Down Payment)", 12, 7.5, ["Private Yacht Marina Slips", "Exclusive Sunset Pavilion", "Hydro-Wellness Treatment Pods", "Private Garden Terraces"], "DLD Escrow #97654 / FAB", false],
  ["DUBAI HARBOUR CRUISE RESIDENCES", "Dubai Harbour Masterplan", "Dubai", "Under Construction", "Apartments", 3400000, "Q1 2028", "1BR, 2BR & 3BR Cruise Waterfront", "60/40 Handover Plan", 40, 8.1, ["Largest Marina in Middle East", "Skydive Dubai Viewpoint", "Private Beachfront Strip", "Michelin Dining Boardwalk"], "DLD Escrow #89110 / Mashreq", true],
  ["CREEK BEACH SEASIDE MANSIONS", "Creek Beach, Dubai Creek", "Dubai", "Ready", "Apartments", 2700000, "Ready for Handover", "2BR & 3BR Beachside Homes", "100% Ready (Immediate Move-In)", 100, 8.3, ["Private 700m White Sand Beach", "Wave Machine Pool", "Licensed Beach Restaurants", "Central Park Connectivity"], "DLD Title Deed Issued", false],
  ["AL RAHA BEACH RESIDENCE TOWERS", "Al Dana, Al Raha Beach", "Abu Dhabi", "Ready", "Apartments", 1350000, "Ready for Handover", "1BR, 2BR & 3BR Channel Suites", "Bank Mortgage Ready", 100, 8.7, ["Canal Promenade Water Taxis", "Rooftop Infinity Pools", "Direct Al Raha Mall Access", "Abu Dhabi Airport 10 Mins"], "AD DMT Title Deed Ready", false],
  ["MARINA SHORES SKYLINE", "Dubai Marina Central", "Dubai", "Under Construction", "Apartments", 2300000, "Q4 2027", "1BR, 2BR & 3BR High-Rise", "70/30 Construction Linked", 52, 8.5, ["Direct Marina Walk Connection", "Panoramic Harbor Views", "State-of-the-Art Fitness Club", "High-Speed Elevators"], "DLD Escrow #87102 / Emirates NBD", false],
  ["YAS PARK SEA RESIDENCES", "Yas Island North Bay", "Abu Dhabi", "Off-Plan", "Apartments", 1550000, "Q3 2028", "1BR, 2BR & 3BR Resort Suites", "60/40 Construction Linked", 18, 9.0, ["Ferrari World & Warner Bros Near", "Resort Swimming Lagoons", "Splash Parks & Cycling Trails", "Padel Courts & Fitness Track"], "AD DMT Escrow #46129 / FAB", false],
  ["CANAL HORIZON VIEW", "Al Wasl / Dubai Canal", "Dubai", "Off-Plan", "Apartments", 2950000, "Q1 2029", "2BR & 3BR Canal Suites", "60/40 (20% Down)", 14, 8.0, ["Safa Park Green Overlook", "Canal Waterway Frontage", "Sky Lounge & Cigar Room", "Infinity Horizon Lap Pool"], "DLD Escrow #96541 / ADCB", false],
  ["DUBAI ISLANDS CORAL BAY", "Island B, Dubai Islands", "Dubai", "Off-Plan", "Apartments", 1800000, "Q4 2028", "1BR & 2BR Island Suites", "70/30 with 2-Year Post Handover", 15, 9.2, ["Direct Beachfront Access", "Resort Marina Slips", "Coral Reef Snorkeling Lagoon", "Island Sunset Beach Club"], "DLD Escrow #98332 / CBD", true],
  ["MINA RASHID SEA VIEW HOMES", "Port Rashid Heritage Marina", "Dubai", "Under Construction", "Apartments", 2100000, "Q2 2028", "1BR, 2BR & 3BR Heritage Marina", "60/40 Construction Linked", 38, 8.4, ["Queen Elizabeth 2 Floating Hotel View", "Canal Pool & Venice Style Bridges", "Floating Yacht Club Access", "Private Beach Club Voucher"], "DLD Escrow #90422 / Emirates NBD", false],
  ["AL REEM CANAL PANORAMA", "Shams Abu Dhabi, Al Reem", "Abu Dhabi", "Ready", "Apartments", 1150000, "Ready for Handover", "Studio, 1BR & 2BR Canal Flats", "Ready with 5-Year Mortgage", 100, 9.5, ["Shams Central Park Access", "Reem Mall 5-Min Walk", "Olympic Swimming Pool", "24/7 Security & Concierge"], "AD DMT Certified", false],
  ["WATERFRONT PROMENADE RETREAT", "Dubai Creek Harbour Canal Edge", "Dubai", "Off-Plan", "Apartments", 2050000, "Q3 2028", "1BR, 2BR & 3BR Promenade Flats", "60/40 Construction Linked", 22, 8.6, ["Bird Sanctuary Nature Overlook", "Promenade Cafes & Gelaterias", "High-Tech Smart Gym", "Rooftop BBQ Stargazing Deck"], "DLD Escrow #94112 / DIB", false]
];

const ultraLuxury = [
  ["VANTAGE SKY PALACE RESIDENCES", "Downtown Dubai Boulevard", "Dubai", "Off-Plan", "Penthouses", 16500000, "Q4 2028", "4BR, 5BR & 6BR Triplex Sky Mansions", "60/40 VIP Payment Plan", 15, 7.1, ["Private Infinity Edge Pool on 75th Floor", "Direct Burj Khalifa Unobstructed Vista", "Private Car Elevator to Penthouse", "Rolls-Royce Chauffeur Fleet"], "DLD Escrow #99101 / FAB", true],
  ["THE ROYAL CRESCENT MANSION", "Palm Jumeirah Billionaires Row", "Dubai", "Under Construction", "Villas", 48000000, "Q1 2027", "6BR, 7BR & 8BR Oceanfront Palaces", "50/50 on Handover", 65, 6.2, ["Private 120m Private Beach", "Indoor & Outdoor Infinity Pools", "Private Yacht Dock & Slipway", "Full Sub-Zero & Boffi Kitchens"], "DLD Escrow #81123 / Emirates NBD", true],
  ["EMIRATES HILLS SIGNATURE ESTATE", "Sector V, Emirates Hills", "Dubai", "Ready", "Villas", 38500000, "Ready for Handover", "6BR & 7BR Fairway Fronting Mansions", "100% Cash / Private Banking", 100, 6.5, ["Championship Montgomerie Golf Views", "Basement 10-Car Showroom Gallery", "Private Wellness Spa & Cryo Chamber", "Staff Quarters for 8"], "DLD Title Deed Ready", true],
  ["BULGARI ISLE MARINA RETREAT", "Jumeirah Bay Island", "Dubai", "Under Construction", "Penthouses", 28000000, "Q3 2027", "4BR & 5BR Marina Penthouses", "70/30 Milestone Linked", 55, 6.8, ["Seahorse Shaped Island Setting", "Exclusive Bulgari Yacht Club Access", "Private Mooring Berth", "Custom Italian Marble & Woodwork"], "DLD Escrow #83441 / Mashreq", true],
  ["ONE CANAL ULTRA LUXE SUITES", "Dubai Water Canal, Safa", "Dubai", "Under Construction", "Penthouses", 19500000, "Q4 2027", "3BR, 4BR & 5BR Canal Penthouses", "60/40 Construction Linked", 48, 7.3, ["Private Sky Pools & Garden Terraces", "Fendi Casa Curated Interiors", "Double Height 7m Ceilings", "Private Elevator Foyers"], "DLD Escrow #85612 / DIB", true],
  ["SAADIYAT RESERVE ROYAL PALACE", "Saadiyat Beach Reserve", "Abu Dhabi", "Off-Plan", "Villas", 24500000, "Q2 2028", "5BR, 6BR & 7BR Dune Mansions", "60/40 (10% Down Payment)", 20, 7.0, ["Direct Saadiyat Turtle Beach Access", "Gary Player Golf Course Direct Frontage", "Sub-Zero Chef Kitchen & Scullery", "Private Tennis & Padel Court"], "AD DMT Escrow #51209 / FAB", true],
  ["DOWNTOWN REGENCY SKY PENTHOUSE", "Opera District, Downtown Dubai", "Dubai", "Under Construction", "Penthouses", 22000000, "Q2 2028", "4BR & 5BR Duplex Sky Suites", "60/40 Construction Linked", 35, 7.4, ["Dubai Opera & Fountain Centerline", "Private Rooftop Infinity Lap Pool", "Sommelier Wine Tasting Lounge", "Private Butler Service"], "DLD Escrow #89901 / ADCB", true],
  ["AL BARARI BOTANICAL PALACE", "The Reserve, Al Barari", "Dubai", "Ready", "Villas", 32000000, "Ready for Handover", "6BR & 7BR Forest Sanctuary Villas", "Ready with 2-Year Payment Plan", 100, 6.9, ["80% Greenery & Freshwater Streams", "Private Spa Sanctuary with Hamam", "Rooftop Stargazing Observatory", "16m Temperature Controlled Lagoon Pool"], "DLD Title Deed Issued", false],
  ["PEARL JUMEIRA WATERFRONT VILLA", "Pearl Jumeira Island", "Dubai", "Under Construction", "Villas", 26000000, "Q1 2028", "5BR & 6BR Private Beach Villas", "70/30 on Completion", 45, 7.2, ["Nikki Beach Club Access", "Direct Gulf Sunset Views", "Basement Bowling & Cinema Suite", "Smart Solar Integration"], "DLD Escrow #87412 / CBD", false],
  ["DUBAI HILLS FAIRWAY MANSION", "Dubai Hills Grove", "Dubai", "Ready", "Villas", 42000000, "Ready for Handover", "7BR Golf Front Estate", "100% Cash / Mortgage", 100, 6.4, ["18-Hole Championship Golf Course", "Burj Khalifa Skyline Vistas", "Full Basement Entertainment Vault", "Commercial Grade Catering Kitchen"], "DLD Title Deed Ready", true],
  ["NURAI ISLAND WATER VILLA", "Nurai Private Island", "Abu Dhabi", "Ready", "Villas", 29500000, "Ready for Handover", "4BR & 5BR Overwater Palaces", "Cash / Bespoke Financing", 100, 7.6, ["Private 15-Minute Speedboat to Saadiyat", "Overwater Hammocks & Private Beach", "Helipad Landing Permissions", "Full Hotel Rental Pool Option"], "AD DMT Certified", false],
  ["CANAL PALACE DUPLEX SUITES", "Business Bay Marasi Drive", "Dubai", "Off-Plan", "Penthouses", 14500000, "Q1 2029", "3BR & 4BR Marina Duplexes", "60/40 Construction Linked", 10, 7.8, ["Canal Promenade Frontage", "Private Jacuzzi Terraces", "High-Security Biometric Lifts", "Private Valet Bays"], "DLD Escrow #97110 / Emirates NBD", false],
  ["JUMEIRAH ISLANDS MASTER MANSION", "Jumeirah Islands Main Lake", "Dubai", "Ready", "Villas", 18500000, "Ready for Handover", "5BR & 6BR Lakefront Villas", "Mortgage Approved", 100, 7.0, ["Private Cascading Waterfall Pool", "Panoramic Lake Island Views", "Renovated Modern Italian Finishes", "Gated Ultra-Secure Community"], "DLD Title Deed Cleared", false],
  ["DUBAI CREEK HARBOUR SKY MANSION", "The Island District, DCH", "Dubai", "Under Construction", "Penthouses", 17500000, "Q3 2027", "4BR & 5BR Sky Mansions", "70/30 Handover Linked", 50, 7.5, ["360 Degree Lagoon & Skyline Views", "Private Elevator Access", "Designer Poliform Italian Closets", "Dedicated Yacht Club Membership"], "DLD Escrow #86329 / FAB", false],
  ["PALM JEBEL ALI SIGNATURE VILLA", "Frond M, Palm Jebel Ali", "Dubai", "Off-Plan", "Villas", 21000000, "Q4 2029", "5BR & 6BR Coral Beachfront Mansions", "60/40 (20% Down)", 8, 8.5, ["Double Sized Beach Plot", "Crystal Blue Waters Frontage", "Smart Eco Climate Design", "Private Marina Mooring Option"], "DLD Escrow #99801 / Emirates NBD", true],
  ["CITY WALK LUXE SKY APEX", "Central Park, City Walk", "Dubai", "Under Construction", "Penthouses", 13500000, "Q4 2027", "4BR Penthouse with Sky Garden", "60/40 on Completion", 52, 7.9, ["Lush Central Park Direct Frontage", "Private Glass Infinity Pool", "Smart Climate Green Glass", "Rooftop Zen Garden & Firepit"], "DLD Escrow #88210 / ADCB", false],
  ["AL GURM CORNICE MANSION", "Al Gurm Resort & Mangroves", "Abu Dhabi", "Ready", "Villas", 35000000, "Ready for Handover", "6BR Mangrove Eco-Luxe Palace", "100% Cash / Sovereign Wealth", 100, 6.7, ["Protected Mangrove Sanctuary Waterway", "Private Boat Slipway & Jetty", "Solar Powered Smart Estate", "24/7 Diplomatic Grade Security"], "AD DMT Title Deed Ready", false],
  ["ZA'ABEEL HIGH PALACE SKY SUITES", "Za'abeel 1, Near DIFC", "Dubai", "Under Construction", "Penthouses", 15800000, "Q2 2028", "3BR & 4BR Cantilever Penthouses", "60/40 Construction Linked", 40, 7.7, ["World's Longest Cantilever Sky Bridge", "Michelin Star Private Dining Hub", "Direct DIFC & Dubai Frame Views", "Executive Helipad Access"], "DLD Escrow #90214 / FAB", false],
  ["DISTRICT ONE SIGNATURE PALACE", "District One, MBR City", "Dubai", "Under Construction", "Villas", 31000000, "Q1 2028", "6BR & 7BR Contemporary Palaces", "60/40 Handover Linked", 44, 7.1, ["Direct Crystal Lagoon Access", "8.4km Cycling & Running Track", "Basement Home Cinema & Wine Cellar", "Private Lift & Staff Wing"], "DLD Escrow #89452 / Emirates NBD", false],
  ["DUBAI WATER CANAL SIGNATURE APEX", "Jumeirah Canal Side", "Dubai", "Off-Plan", "Penthouses", 23500000, "Q3 2028", "4BR & 5BR Water Penthouses", "60/40 Construction Linked", 22, 7.3, ["Unobstructed Arabian Gulf & Canal Views", "Private 20m Rooftop Lap Pool", "Private Butler & Valet Quarters", "Direct Marina Slipway"], "DLD Escrow #94210 / DIB", false],
  ["SAADIYAT ISLAND RESERVE VILLA", "Cultural District, Saadiyat", "Abu Dhabi", "Off-Plan", "Villas", 19800000, "Q4 2028", "5BR & 6BR Reserve Mansions", "60/40 Milestone Linked", 16, 7.2, ["Walking Distance to Guggenheim", "Lush Native Botanical Gardens", "Private Spa Pavilion & Lap Pool", "Smart Biometric Security"], "AD DMT Escrow #49210 / ADIB", false],
  ["EMIRATES CROWN DUPLEX PENTHOUSE", "Dubai Marina North Edge", "Dubai", "Ready", "Penthouses", 12500000, "Ready for Handover", "4BR & 5BR Full Floor Penthouse", "Ready Cash / Bank Mortgage", 100, 8.0, ["360 Sky Views of Marina & Palm", "Private Terrace with Plunge Jacuzzi", "Bespoke Onyx Marble Finishes", "4 Dedicated Basement Parking Bays"], "DLD Title Deed Issued", false],
  ["JUMEIRAH GOLF ESTATES ROYAL VILLA", "Flame Tree Ridge, JGE", "Dubai", "Ready", "Villas", 22000000, "Ready for Handover", "5BR & 6BR Tuscan Golf Mansions", "Immediate Handover", 100, 6.9, ["Earth Championship Golf Frontage", "Sub-Zero Kitchen & Wine Vault", "Infinity Edge Heated Swimming Pool", "Clubhouse VIP Privileges"], "DLD Title Deed Ready", false],
  ["BLUEWATERS ULTRA SUITE RESIDENCES", "Bluewaters Island", "Dubai", "Ready", "Penthouses", 18200000, "Ready for Handover", "4BR Penthouse with Ain Dubai Frontage", "Cash / Private Mortgage", 100, 7.4, ["Exclusive Island Waterfront", "Caesars Palace Hospitality Amenities", "Private Yacht Mooring Option", "24/7 Dedicated Butler Desk"], "DLD Title Deed Cleared", false],
  ["DUBAI HILLS PARKVIEW PALACE", "Parkways, Dubai Hills Estate", "Dubai", "Under Construction", "Villas", 27500000, "Q2 2028", "6BR Golf View Modern Palace", "60/40 Milestone Linked", 36, 7.0, ["Direct Dubai Hills Central Park Frontage", "Smart Zero-Carbon Solar Roof", "Basement Bowling Alley & Spa", "Panoramic Burj Khalifa Rooftop Lounge"], "DLD Escrow #91223 / Emirates NBD", false],
  ["PALM JUMEIRAH SUNSET CROWN", "Frond K, Palm Jumeirah", "Dubai", "Under Construction", "Villas", 44000000, "Q3 2027", "6BR Custom Beachfront Estate", "70/30 on Completion", 58, 6.3, ["Sunset Facing Private White Sand Beach", "Infinity Edge Lagoon with Fire Features", "Imported Travertine Stone & Italian Kitchen", "Automated Security Perimeter"], "DLD Escrow #84551 / Mashreq", true]
];

const golfAndVillas = [
  ["VANTAGE FAIRWAYS ESTATE", "Dubai Hills Estate Golf Course", "Dubai", "Off-Plan", "Villas", 7800000, "Q4 2028", "4BR & 5BR Fairway Linked Villas", "60/40 Construction Linked", 16, 7.9, ["Championship Golf Course Access", "Dubai Hills Mall Connection", "Private Landscaped Garden", "Kids Splash & Adventure Park"], "DLD Escrow #99312 / Emirates NBD", true],
  ["DAMAC LAGOONS MYKONOS VILLA", "DAMAC Lagoons, Dubailand", "Dubai", "Under Construction", "Townhouses", 2850000, "Q2 2027", "4BR & 5BR Mediterranean Townhouses", "70/30 Handover Linked", 62, 8.8, ["Crystal Swimmable Lagoon", "Gondola Rides & Water Cinema", "Sandy Beachfront & Beach Club", "Kids Water Sports Arena"], "DLD Escrow #82109 / DIB", true],
  ["TILAL AL GHAF HARMONY VILLA", "Tilal Al Ghaf Master Community", "Dubai", "Under Construction", "Villas", 5400000, "Q1 2028", "4BR & 5BR Garden Suite Villas", "60/40 Handover Linked", 46, 8.2, ["Lagoon Al Ghaf Crystal Waters", "18km Dedicated Cycling Network", "Royal Grammar School Guildford on Site", "Private Garden Pods"], "DLD Escrow #88410 / FAB", true],
  ["ARABIAN RANCHES III PARKSIDE", "Arabian Ranches III", "Dubai", "Ready", "Townhouses", 2450000, "Ready for Handover", "3BR & 4BR Modern Park Townhouses", "100% Ready (Immediate Handover)", 100, 8.6, ["Lazy River & Splash Waterpark", "Central Park with Outdoor Cinema", "Clubhouse & Fitness Center", "Retail Souk with Spinneys"], "DLD Title Deed Ready", false],
  ["SOBHA HARTLAND FOREST VILLAS", "Sobha Hartland, MBR City", "Dubai", "Under Construction", "Villas", 8900000, "Q3 2027", "4BR & 5BR Forest Sanctuary Villas", "70/30 Milestone Linked", 54, 7.7, ["North London Collegiate School Near", "Private Gated Forest Trail", "Glass Elevator & Infinity Pool", "2 Minutes to Ras Al Khor Sanctuary"], "DLD Escrow #85122 / ADCB", true],
  ["YAS ACRES GOLF COUNTRY VILLAS", "Yas Acres, Yas Island", "Abu Dhabi", "Ready", "Villas", 4100000, "Ready for Handover", "3BR, 4BR & 5BR Golf & Park Villas", "Ready with 3-Year Payment Plan", 100, 8.5, ["9-Hole Floodlit Golf Course", "Country Club & Olympic Pool", "Tennis, Squash & Basketball Courts", "Yas Marina & Theme Parks 5 Mins"], "AD DMT Certified", true],
  ["JUBAIL ISLAND MANGROVE VILLAS", "Jubail Island Sanctuary", "Abu Dhabi", "Under Construction", "Villas", 6200000, "Q2 2028", "4BR, 5BR & 6BR Mangrove Eco Villas", "60/40 (10% Down)", 38, 7.8, ["Mangrove Kayaking & Nature Boardwalks", "Private Beach Club & Marina", "Boutique Village Center & Cafes", "Low Density Eco Sanctuary"], "AD DMT Escrow #54312 / FAB", true],
  ["THE OASIS PALM ESTATE", "The Oasis by Emaar, Dubailand", "Dubai", "Off-Plan", "Villas", 9800000, "Q1 2029", "4BR & 5BR Resort Mansions", "60/40 Construction Linked", 12, 8.0, ["Interconnected Swimmable Waterways", "Resort Style Wellness Sanctuary", "World-Class Golf Course", "Private Island Pocket Communities"], "DLD Escrow #98412 / Emirates NBD", true],
  ["AL RANIM MUDON TOWNHOMES", "Mudon Master Community", "Dubai", "Under Construction", "Townhouses", 2300000, "Q4 2027", "3BR & 4BR Single Row Townhomes", "60/40 Construction Linked", 50, 8.9, ["Mudon Central Park Frontage", "Dog Park & Community Sports Hub", "Children Adventure Playground", "Community Centre & Supermarkets"], "DLD Escrow #87612 / DIB", false],
  ["VALLEY RIDGE PARK VILLAS", "The Valley by Emaar, Al Ain Rd", "Dubai", "Under Construction", "Townhouses", 1950000, "Q1 2028", "3BR & 4BR Modern Countryside Villas", "70/30 on Completion", 42, 9.1, ["Golden Beach & Water Splash", "Sports Village with Tennis & Football", "Town Centre Farmers Market", "Pocket Parks & Cycling Tracks"], "DLD Escrow #89144 / Emirates NBD", false],
  ["VILLANOVA LA ROSA HOMES", "Villanova, Dubailand", "Dubai", "Ready", "Townhouses", 2150000, "Ready for Handover", "3BR & 4BR Mediterranean Townhouses", "Mortgage Ready", 100, 8.7, ["Linear Parks & Jogging Paths", "Community Pools & Barbecue Areas", "GEMS FirstPoint School Nearby", "Al Habtoor Polo Resort 5 Mins"], "DLD Title Deed Ready", false],
  ["DAMAC HILLS SILVER SPRINGS", "DAMAC Hills 1 Golf Community", "Dubai", "Ready", "Villas", 4800000, "Ready for Handover", "4BR & 5BR Trump Golf Villas", "Ready with 2-Year Post-Handover", 100, 8.3, ["Trump International Golf Club Dubai", "Malibu Bay Artificial Wave Pool", "Stables & Petting Farm", "Radisson Dubai DAMAC Hills Hotel"], "DLD Title Deed Cleared", false],
  ["DUBAI SOUTH GREENFIELD ESTATES", "Dubai South Residential District", "Dubai", "Off-Plan", "Townhouses", 1650000, "Q3 2028", "3BR & 4BR Townhouses", "50/50 Post-Handover Plan", 18, 9.5, ["Al Maktoum International Airport 10 Mins", "Direct Metro Blue Line Link", "Lush Linear Parks & Retail Souk", "Expo City Dubai 5-Min Drive"], "DLD Escrow #96120 / Mashreq", true],
  ["SAADIYAT LAGOONS RETREAT", "Saadiyat Island Nature Reserve", "Abu Dhabi", "Under Construction", "Villas", 7200000, "Q4 2027", "4BR, 5BR & 6BR Wilderness Villas", "60/40 Construction Linked", 44, 8.1, ["Eco-Protected Forest Living", "Padel Courts & Skatepark", "Open Air Cinema & Farmers Market", "Cranleigh Abu Dhabi School Proximity"], "AD DMT Escrow #53110 / ADCB", false],
  ["CHERRYWOODS RETREAT HOMES", "Cherrywoods, Al Qudra Road", "Dubai", "Ready", "Townhouses", 2600000, "Ready for Handover", "3BR & 4BR Modern Townhouses", "Ready for Move-In", 100, 8.4, ["Central Lake & Community Club", "Squash & Tennis Courts", "Al Qudra Cycling Track Nearby", "Gated Security & CCTV"], "DLD Title Deed Ready", false],
  ["TILAL AL FURJAN MEADOWS", "Al Furjan South, Jebel Ali", "Dubai", "Under Construction", "Villas", 4300000, "Q2 2027", "4BR & 5BR Luxury Family Villas", "70/30 Handover Linked", 58, 8.2, ["Al Furjan Pavilion & Metro Station", "Private Swimming Pool Option", "Landscaped Walkways & Playgrounds", "Ibn Battuta Mall 7 Mins"], "DLD Escrow #84199 / FAB", false],
  ["SERENIA LIVING PALM VILLAS", "Palm Jumeirah East Boardwalk", "Dubai", "Under Construction", "Penthouses", 18900000, "Q1 2028", "4BR Beachfront Sky Mansions", "60/40 Handover Linked", 36, 7.3, ["Direct Private Beach Cabanas", "Paddle Board & Kayak Club", "Private Cinema & Executive Lounge", "Rolls Royce Airport Transfers"], "DLD Escrow #90119 / Emirates NBD", true],
  ["DUBAI HILLS SIDRA RETREAT", "Sidra 3, Dubai Hills Estate", "Dubai", "Ready", "Villas", 5900000, "Ready for Handover", "4BR & 5BR Modern Independent Villas", "Cash / Mortgage Ready", 100, 7.8, ["Walk to Dubai Hills Park", "Community Pool & Tennis Club", "King's College Hospital Proximity", "Bespoke Landscaped Pergola"], "DLD Title Deed Ready", false],
  ["HAYAT ISLAND BEACH VILLAS", "Hayat Island, Mina Al Arab", "Ras Al Khaimah", "Under Construction", "Villas", 3200000, "Q3 2027", "3BR & 4BR Coastal Beach Villas", "60/40 Construction Linked", 52, 9.2, ["Wynn Casino Al Marjan 10 Mins", "Direct Beach & Lagoon Access", "InterContinental Resort Amenities", "Flamingo Lagoon Nature Trails"], "RAK Municipality Escrow #33201", true],
  ["AL REEF 2 CANAL VILLAS", "Al Samha, Abu Dhabi", "Abu Dhabi", "Ready", "Townhouses", 1600000, "Ready for Handover", "3BR Modern Family Villas", "100% Cash / Bank Mortgage", 100, 9.4, ["Abu Dhabi - Dubai Highway Access", "Community Center with Carrefour", "Multiple Swimming Pools", "Gated Family Friendly Setting"], "AD DMT Certified", false],
  ["RUKAN TOWER & TOWNHOUSES", "Rukan Community, Wadi El Safa", "Dubai", "Ready", "Townhouses", 1400000, "Ready for Handover", "2BR & 3BR Modern Townhomes", "Ready with 3-Year Post Handover", 100, 9.6, ["70% Open Space & Greenery", "Running & Cycling Tracks", "Multiple Clubhouse Pools", "Hamdan Sports Complex Nearby"], "DLD Title Deed Cleared", false],
  ["GRAND POLO CLUB & RESORT VILLAS", "Grand Polo Club, Dubailand", "Dubai", "Off-Plan", "Villas", 6800000, "Q4 2028", "4BR & 5BR Equestrian Villas", "60/40 Construction Linked", 14, 8.0, ["Direct Polo Field Views & Stables", "Equestrian Academy & Riding School", "Private Organic Farm & Orchard", "Clubhouse Michelin Brasserie"], "DLD Escrow #98102 / Emirates NBD", true],
  ["NAD AL SHEBA GARDENS ESTATE", "Nad Al Sheba 1, Meydan", "Dubai", "Under Construction", "Villas", 5100000, "Q2 2028", "3BR, 4BR & 5BR Modern Heritage Homes", "60/40 Milestone Linked", 32, 8.3, ["Meydan Racecourse Views", "Lush Organic Community Gardens", "Deep Lagoon & Wave Pool", "10 Mins to Downtown Dubai"], "DLD Escrow #92410 / DIB", false],
  ["JASMINE LANE BY ELIE SAAB", "Jumeirah Golf Estates", "Dubai", "Under Construction", "Townhouses", 3900000, "Q4 2027", "3BR & 4BR Elie Saab Branded Townhouses", "70/30 Handover Linked", 48, 8.4, ["Interiors by Elie Saab Haute Couture", "Golf Simulator & Wellness Hub", "Lagoon Swimming Pool", "Gated Ultra-Private Compound"], "DLD Escrow #88290 / Mashreq", false],
  ["AL JADAF WATERFRONT PARK VILLAS", "Culture Village, Al Jaddaf", "Dubai", "Ready", "Townhouses", 3400000, "Ready for Handover", "3BR & 4BR Waterfront Townhouses", "Ready for Move-In", 100, 8.6, ["Dubai Creek Skyline Views", "Jameel Arts Centre Proximity", "Al Jaddaf Metro 3-Min Walk", "Private Rooftop Terraces"], "DLD Title Deed Ready", false],
  ["YAS GOLF COLLECTION DUPLEXES", "Yas Island Golf Course", "Abu Dhabi", "Under Construction", "Apartments", 2100000, "Q1 2028", "2BR & 3BR Golf Duplexes", "60/40 Construction Linked", 40, 8.9, ["Yas Links Championship Golf Front", "Direct Access to Yas Theme Parks", "Rooftop Pools & Yoga Deck", "Short-Term Rental Permit Included"], "AD DMT Escrow #51020 / FAB", false],
  ["PARKWAY VISTAS FAIRWAY HOMES", "Dubai Hills Parkway", "Dubai", "Ready", "Villas", 14500000, "Ready for Handover", "6BR Golf Facing Custom Villa", "Mortgage Ready", 100, 7.2, ["Full Golf Course & Skyline Panorama", "Private 15m Heated Swimming Pool", "Smart Gira Home Automation", "Italian Imported Quartz & Wood"], "DLD Title Deed Issued", true],
  ["EXPO VALLEY SMART TOWNHOUSES", "Expo City Dubai, Dubai South", "Dubai", "Under Construction", "Townhouses", 3600000, "Q3 2027", "3BR & 4BR Net-Zero Townhouses", "60/40 Construction Linked", 50, 8.7, ["Native Gazelle Nature Reserve", "100% Pedestrianized Community", "Expo City Pavilions Walking Distance", "Solar Powered Smart Microgrid"], "DLD Escrow #86921 / Emirates NBD", true]
];

const urbanHighYield = [
  ["VANTAGE CENTRAL METROPOLIS", "Business Bay Financial Core", "Dubai", "Off-Plan", "Apartments", 1250000, "Q4 2028", "Studio, 1BR & 2BR High-Yield Units", "50/50 Post-Handover (1% Monthly)", 16, 9.4, ["1-Min to Business Bay Metro", "Co-working & Podcast Pods", "Rooftop Infinity Sky Lounge", "Automated Airbnb License Portal"], "DLD Escrow #99401 / CBD", true],
  ["DOWNTOWN ELEVATE SUITES", "Downtown Dubai, Burj Crown Way", "Dubai", "Under Construction", "Apartments", 1950000, "Q2 2027", "1BR & 2BR Luxury Urban Flats", "70/30 on Completion", 60, 8.7, ["Burj Khalifa Centerline Views", "Dubai Mall 4-Minute Walk", "24/7 Hotel Style Concierge", "High Occupancy Guarantee 9%"], "DLD Escrow #83912 / Emirates NBD", true],
  ["JVC HIGH-LINE STUDIOS", "Jumeirah Village Circle District 14", "Dubai", "Ready", "Apartments", 680000, "Ready for Handover", "Executive Studios & 1BR Smart Units", "Ready with 2-Year Rental Guarantee", 100, 10.2, ["Circle Mall 2-Min Walk", "Fully Furnished by Italian Designers", "Rooftop Padel & Sun Deck", "Smart Door Lock Integration"], "DLD Title Deed Ready", true],
  ["ARJAN EMPIRE TOWERS", "Arjan, Al Barsha South", "Dubai", "Under Construction", "Apartments", 740000, "Q1 2028", "Studio & 1BR Investment Apartments", "60/40 (1% Monthly Payment)", 44, 9.8, ["Dubai Miracle Garden Frontage", "Rooftop Cinema & BBQ Zone", "High-Tech Fitness Studio", "Direct Hessa Street Access"], "DLD Escrow #87512 / DIB", false],
  ["AL JADAF METRO SUITES", "Al Jaddaf Cultural Zone", "Dubai", "Ready", "Apartments", 920000, "Ready for Handover", "1BR & 2BR City View Suites", "100% Ready (Immediate Tenancy)", 100, 9.1, ["Al Jaddaf Metro Station 100m", "Dubai Healthcare City 3 Mins", "Infinity Creek View Pool", "High Corporate Tenant Demand"], "DLD Title Deed Cleared", false],
  ["MEYDAN HORIZON APARTMENTS", "Meydan One Masterplan", "Dubai", "Off-Plan", "Apartments", 1100000, "Q3 2028", "Studio, 1BR & 2BR Meydan Suites", "60/40 Construction Linked", 22, 9.3, ["Meydan Racecourse Views", "Crystal Lagoon Walkway Access", "Direct Al Khail Road Access", "Electric Scooter Charging Stations"], "DLD Escrow #94321 / FAB", true],
  ["DUBAI SILICON TECH HUB TOWER", "Dubai Silicon Oasis Central", "Dubai", "Ready", "Apartments", 620000, "Ready for Handover", "Studio & 1BR Tech Furnished Units", "Ready with 8.5% Net Return", 100, 9.9, ["Silicon Central Mall Proximity", "High-Speed 1Gbps Fiber Infrastructure", "Podium Co-Working Workspaces", "University City Academic Zone"], "DLD Title Deed Ready", false],
  ["DUBAI SOUTH AEROTROPOLIS SUITES", "Dubai South Residential City", "Dubai", "Off-Plan", "Apartments", 710000, "Q4 2028", "Studio & 1BR Airport Corridor Units", "50/50 Post Handover Plan", 14, 10.5, ["Al Maktoum Airport Expansion Zone", "Free Zone Worker Tenant Base", "Olympic Swimming Pool & Gym", "Blue Line Metro Planned Station"], "DLD Escrow #98210 / CBD", true],
  ["JLT EXECUTIVE METROPOLIS", "Cluster V, Jumeirah Lakes Towers", "Dubai", "Ready", "Apartments", 1380000, "Ready for Handover", "1BR & 2BR High Floor Lake Suites", "Ready for Move-In / Mortgage", 100, 8.8, ["DMCC Freezone Business Hub", "Lake Promenade Cafes & Restaurants", "DMCC Metro Station 3-Min Walk", "Full Floor Wellness Club"], "DLD Title Deed Issued", false],
  ["AL FURJAN METRO PLAZA", "Al Furjan Metro East", "Dubai", "Under Construction", "Apartments", 880000, "Q4 2027", "Studio, 1BR & 2BR Transit Apartments", "60/40 Construction Linked", 52, 9.2, ["Direct 50m Footbridge to Metro", "Ibn Battuta Mall 5 Mins", "Smart Keyless Building Entry", "Rooftop Swimming Pool"], "DLD Escrow #86551 / Emirates Islamic", false],
  ["STUDIO CITY MEDIA TOWER", "Dubai Studio City", "Dubai", "Under Construction", "Apartments", 690000, "Q1 2028", "Studio & 1BR Media Production Suites", "70/30 on Handover", 38, 9.6, ["Media Hub & Creative Studios", "Outdoor Amphitheater & Cinema", "Soundproof Co-working Pods", "Motor City Dining Strip 2 Mins"], "DLD Escrow #89102 / DIB", false],
  ["DUBAI SCIENCE PARK HEIGHTS", "Dubai Science Park, Barsha South", "Dubai", "Off-Plan", "Apartments", 820000, "Q3 2028", "Studio, 1BR & 2BR Eco Units", "60/40 (1% Per Month)", 20, 9.5, ["Biotech & Pharma Corporate Hub", "Neuro Spinal Hospital Near", "Solar Powered Facilities", "Rooftop Yoga & Plunge Pool"], "DLD Escrow #93120 / Mashreq", false],
  ["SPORTS CITY STADIUM RESIDENCES", "Dubai Sports City", "Dubai", "Ready", "Apartments", 720000, "Ready for Handover", "1BR & 2BR Stadium View Units", "Ready with Instant Rent Yield", 100, 9.3, ["ICC Cricket Stadium Frontage", "Els Club Championship Golf 3 Mins", "Olympic Swimming Academy", "Easy Hessa & Sheikh Zayed Road"], "DLD Title Deed Ready", false],
  ["MAJAN CITADEL SUITES", "Majan, Dubailand", "Dubai", "Off-Plan", "Apartments", 640000, "Q2 2029", "Studio & 1BR Smart Units", "50/50 with 3-Year Post-Handover", 10, 10.1, ["Global Village 5 Mins", "IMG Worlds of Adventure 4 Mins", "Rooftop Infinity Lagoon", "Boutique Retail Concourse"], "DLD Escrow #98910 / CBD", false],
  ["AL SUFOUH TECH VIEW SUITES", "Dubai Internet City / Al Sufouh", "Dubai", "Under Construction", "Apartments", 1450000, "Q3 2027", "1BR & 2BR Corporate Residences", "70/30 on Handover", 58, 8.6, ["Internet City & Media City 2 Mins", "Palm Jumeirah & Sea Horizon View", "Executive Business Lounge", "Smart Meeting Suites"], "DLD Escrow #84102 / FAB", false],
  ["AL REEM SKYRISE SUITES", "Shams Sector, Al Reem Island", "Abu Dhabi", "Ready", "Apartments", 890000, "Ready for Handover", "1BR & 2BR High-Floor Units", "Ready Cash / 80% Mortgage", 100, 9.4, ["Direct Shams Mall Link", "High Yield Expat Rental Corridor", "Sea & Canal Dual Panorama", "Gym, Sauna & Jacuzzi Hub"], "AD DMT Certified", false],
  ["DISCOVERY GARDENS OASIS TOWER", "Discovery Gardens Metro Corridor", "Dubai", "Ready", "Apartments", 580000, "Ready for Handover", "Studio & 1BR High Yield Units", "Ready 100% Cash / Mortgage", 100, 10.4, ["Direct Metro Route 2020", "Ibn Battuta Mall Walking Distance", "Community Swimming Pools", "Immediate High Rental Return"], "DLD Title Deed Ready", false],
  ["LIVERY TOWER BUSINESS BAY", "Marasi Business Bay", "Dubai", "Under Construction", "Apartments", 1320000, "Q2 2028", "1BR & 2BR Canal View High Rises", "60/40 Construction Linked", 40, 8.9, ["Canal Boardwalk Living", "Downtown Skyline Direct Line", "Co-working Lounge & Espresso Bar", "High Yield Airbnb Ready"], "DLD Escrow #91204 / ADCB", false],
  ["TOWN SQUARE PARK RESIDENCES", "Town Square by Nshama", "Dubai", "Ready", "Apartments", 850000, "Ready for Handover", "1BR & 2BR Park Facing Units", "Immediate Handover Ready", 100, 9.0, ["Central 50,000 sqm Town Park", "Carousel, Splash Pad & Skate Park", "Spinneys & 20+ Cafes in Plaza", "High Family Rental Occupancy"], "DLD Title Deed Cleared", false],
  ["MEYDAN AVENUE COMMERCE FLATS", "Meydan Avenue, Nad Al Sheba", "Dubai", "Under Construction", "Apartments", 1280000, "Q1 2028", "1BR & 2BR Executive Residences", "70/30 on Completion", 46, 8.8, ["Meydan Grandstand Frontage", "5 Mins to Downtown Dubai", "Infinity Rooftop Lounge", "Smart EV Superchargers"], "DLD Escrow #88129 / DIB", false],
  ["CITY WALK PARK GATE APARTMENTS", "City Walk North Gateway", "Dubai", "Under Construction", "Apartments", 2100000, "Q4 2027", "1BR & 2BR Parkside Suites", "60/40 Milestone Linked", 50, 8.3, ["City Walk Retail Piazza 100m", "Central Park Direct Green Views", "Coca-Cola Arena 3 Mins", "High Premium Rental Yields"], "DLD Escrow #85901 / FAB", false],
  ["JVC CIRCLE SQUARE SUITES", "JVC District 10", "Dubai", "Off-Plan", "Apartments", 720000, "Q4 2028", "Studio & 1BR Smart Units", "60/40 (1% Monthly)", 18, 9.7, ["Circle Mall 5-Min Walk", "Resort Pool & Sun Deck", "Private Padel Court", "Smart Alexa Enabled Units"], "DLD Escrow #96411 / Emirates NBD", false],
  ["DUBAI HEALTHCARE CITY TOWER", "DHCC Phase 2, Al Jaddaf", "Dubai", "Under Construction", "Apartments", 1150000, "Q2 2028", "1BR & 2BR Medical Corridor Suites", "60/40 Construction Linked", 35, 9.1, ["High Demand Doctor/Expat Tenant Base", "Dubai Creek Views", "Wellness Hydrotherapy Pool", "Metro Connection Shuttle"], "DLD Escrow #91402 / CBD", false],
  ["PRODUCTION CITY URBAN TOWER", "Dubai Production City (IMPZ)", "Dubai", "Ready", "Apartments", 590000, "Ready for Handover", "Studio & 1BR Budget Yield Units", "Ready with 9.8% Proven ROI", 100, 10.6, ["City Centre Me'aisem 3-Min Walk", "Sheikh Mohammed Bin Zayed Rd Link", "Resort Style Community Pool", "Low Service Charge Advantage"], "DLD Title Deed Ready", false],
  ["AL BARSHA SKY RESIDENCES", "Al Barsha 1, Near Mall of the Emirates", "Dubai", "Ready", "Apartments", 980000, "Ready for Handover", "1BR & 2BR Metro Accessible Units", "Mortgage Ready", 100, 8.9, ["Mall of the Emirates 5-Min Walk", "Red Line Metro Access", "High Short-Term Tourism Yield", "Rooftop Pool & Health Spa"], "DLD Title Deed Issued", false],
  ["DUBAI HILLS COLLECTIVE SUITES", "Dubai Hills Estate Business Park", "Dubai", "Ready", "Apartments", 1120000, "Ready for Handover", "1BR & 2BR Co-Living Units", "Cash / Bank Mortgage", 100, 8.7, ["Trendy Co-Working & Social Lounges", "Outdoor Cinema & Padel Courts", "Dubai Hills Mall Walking Distance", "Young Professional Tenant Hub"], "DLD Title Deed Ready", true],
  ["WASL GATE METRO TOWER", "Wasl Gate, Jebel Ali", "Dubai", "Under Construction", "Apartments", 840000, "Q1 2028", "Studio, 1BR & 2BR Smart Units", "60/40 Construction Linked", 42, 9.3, ["Energy Metro Station Footbridge", "Festival Plaza & IKEA Nearby", "Community Central Park", "Direct Sheikh Zayed Road Access"], "DLD Escrow #88419 / FAB", false],
  ["DUBAI MARINA CORONA SUITES", "Dubai Marina North", "Dubai", "Ready", "Apartments", 1650000, "Ready for Handover", "1BR Waterfront Investment Unit", "Ready with Instant Airbnb Yield", 100, 8.6, ["Marina Promenade Frontline", "High Holiday Home Demand", "Marina Tram Station 2 Mins", "Full Sea & Marina Views"], "DLD Title Deed Ready", false],
  ["AL WARSAN HIGH-YIELD APARTMENTS", "International City Phase 2", "Dubai", "Ready", "Apartments", 480000, "Ready for Handover", "Studio & 1BR High Yield Units", "Ready with 10.8% Net ROI", 100, 11.2, ["Academic City & Silicon Oasis 5 Mins", "Dragon Mart 7-Min Drive", "Very Low Capital Entry Price", "Full In-House Property Management"], "DLD Title Deed Ready", false],
  ["MEYDAN ONE CANAL FLATS", "Meydan One Waterway", "Dubai", "Off-Plan", "Apartments", 1180000, "Q1 2029", "1BR & 2BR Waterway Units", "60/40 (10% Down Payment)", 12, 9.4, ["World's Longest Indoor Ski Slope Near", "Canal Water Taxis", "Rooftop Glass Swimming Pool", "Fast Capital Appreciation Potential"], "DLD Escrow #97551 / Emirates NBD", true]
];

const masterCommunityOffPlan = [
  ["VANTAGE OASIS PHASE 1", "The Oasis Master Community", "Dubai", "Off-Plan", "Villas", 8500000, "Q4 2028", "4BR & 5BR Luxury Water Villas", "60/40 Construction Linked", 15, 8.2, ["Crystal Blue Swimmable Lagoons", "Private Marina Boardwalk", "18-Hole Championship Golf Course", "Eco-Smart District Microgrid"], "DLD Escrow #99512 / Emirates NBD", true],
  ["DUBAI SOUTH LAGOONS PHASE 2", "The Lagoons, Dubai South", "Dubai", "Off-Plan", "Townhouses", 1850000, "Q3 2028", "3BR & 4BR Lagoon Townhouses", "50/50 Post-Handover Plan", 18, 9.6, ["Direct Swimmable Crystal Lagoon", "Al Maktoum Airport 10 Mins", "Expo City Dubai 5 Mins", "Metro Blue Line Station Link"], "DLD Escrow #98114 / FAB", true],
  ["DAMAC RIVERSIDE GREEN RETREAT", "DAMAC Riverside, Investment Park", "Dubai", "Off-Plan", "Townhouses", 1990000, "Q2 2028", "4BR & 5BR Watercourse Townhouses", "70/30 on Completion", 24, 9.1, ["Hydroponic Urban Farm & Culinary Park", "Waterborne Amphitheatre", "Aquatic Fitness Zones", "Floating Sports Pavilions"], "DLD Escrow #96112 / DIB", true],
  ["SOBHA CENTRAL PARK PHASE 4", "Sobha Hartland II", "Dubai", "Off-Plan", "Apartments", 1550000, "Q1 2029", "1BR, 2BR & 3BR Park High-Rises", "60/40 Construction Linked", 12, 8.8, ["Dual Crystal Blue Lagoons", "Over 1 Million Sqft Green Space", "Direct Ras Al Khor Wildlife Overlook", "Downtown Dubai 7 Mins"], "DLD Escrow #97223 / ADCB", true],
  ["THE VALLEY ALANA TOWNHOUSES", "The Valley Phase 2, Emaar", "Dubai", "Off-Plan", "Townhouses", 2150000, "Q4 2028", "3BR & 4BR Stream Facing Homes", "60/40 Construction Linked", 16, 9.0, ["Natural Stream & Wetland Trails", "Golden Sand Beach & Wave Pool", "Sports Village & Padel Complex", "Al Ain Road Direct Flyover"], "DLD Escrow #96811 / Emirates NBD", true],
  ["TILAL AL GHAF ELYSIAN RESERVE", "Elysian Mansions, Tilal Al Ghaf", "Dubai", "Off-Plan", "Villas", 19500000, "Q2 2028", "5BR & 6BR Master Custom Mansions", "60/40 Construction Linked", 25, 7.5, ["Lagoon Al Ghaf Private Beach", "Curated by Bergman Design House", "Basement Wellness Spa & Lounge", "Private Lift & Triple Car Garage"], "DLD Escrow #94110 / Mashreq", true],
  ["PALM JEBEL ALI OASIS VILLA", "Palm Jebel Ali Frond C", "Dubai", "Off-Plan", "Villas", 23500000, "Q1 2029", "5BR & 6BR Coral Beachfront Mansions", "60/40 Milestone Linked", 10, 8.4, ["Private 100m Pristine Beach", "Zero Carbon Smart Infrastructure", "Exclusive Yacht Anchorage", "Dubai's Next Flagship Icon"], "DLD Escrow #99901 / Emirates NBD", true],
  ["CREEK WATERS MASTER TOWER 2", "Dubai Creek Harbour Masterplan", "Dubai", "Off-Plan", "Apartments", 2300000, "Q3 2028", "1BR, 2BR & 3BR Creek Suites", "60/40 Handover Linked", 20, 8.6, ["Burj Khalifa Centerline Panorama", "Creek Marina Promenade Direct Access", "Infinity Sunset Pool Deck", "Smart Automated Home Systems"], "DLD Escrow #95412 / DIB", false],
  ["MUDON AL RANIM PHASE 5", "Mudon Central Hub", "Dubai", "Off-Plan", "Townhouses", 2400000, "Q4 2028", "3BR & 4BR Parkside Townhouses", "60/40 Construction Linked", 22, 8.9, ["Expansive Green Linear Parks", "Children Splash Waterpad", "Community Retail Centre", "Hessa Street Direct Flyover"], "DLD Escrow #95810 / FAB", false],
  ["ARABIAN RANCHES III MAY PHASE", "Arabian Ranches III, Dubailand", "Dubai", "Off-Plan", "Townhouses", 2550000, "Q1 2029", "3BR & 4BR Suburban Family Homes", "60/40 Construction Linked", 14, 8.7, ["Central Park & Clubhouse", "Cricket Ground & Football Pitch", "Spinneys & Blossom Nursery Near", "Al Qudra Cycling Highway Link"], "DLD Escrow #97441 / Emirates NBD", false],
  ["DUBAI HILLS PARK HORIZON", "Dubai Hills Estate Main Boulevard", "Dubai", "Off-Plan", "Apartments", 1750000, "Q4 2028", "1BR, 2BR & 3BR Park Suites", "60/40 Construction Linked", 20, 8.5, ["Dubai Hills Park Direct Frontage", "Dubai Hills Mall 3-Min Walk", "Infinity Skyline Pool", "King's College Hospital Nearby"], "DLD Escrow #96199 / Emirates NBD", false],
  ["SOBHA RESERVE LUXURY PHASE 2", "Sobha Reserve, Wadi Al Safa", "Dubai", "Off-Plan", "Villas", 8200000, "Q2 2029", "4BR & 5BR Biophilic Eco Villas", "60/40 Construction Linked", 12, 8.1, ["25% Forest Tree Canopy", "Private Botanical Gardens & Orchard", "Clubhouse Bouldering & Padel", "Smart Solar Integration"], "DLD Escrow #98221 / ADCB", false],
  ["DAMAC LAGOONS IBIZA RETREAT", "DAMAC Lagoons, Dubailand", "Dubai", "Off-Plan", "Townhouses", 2650000, "Q3 2028", "4BR & 5BR Mediterranean Townhouses", "70/30 Handover Linked", 28, 9.0, ["Sunset DJ Lounge & Tapas Bar", "Boho Courtyard & Hammock Garden", "Crystal Lagoon Water Taxis", "Foam Party Pools & Waterplay"], "DLD Escrow #94881 / DIB", false],
  ["DUBAI SOUTH GREEN BAY RETREAT", "Dubai South Residential", "Dubai", "Off-Plan", "Townhouses", 1720000, "Q1 2029", "3BR & 4BR Family Townhouses", "50/50 Post-Handover (3-Years)", 15, 9.7, ["New Metro Blue Line Hub", "Linear Park Sports Facilities", "Community Club with 4 Pools", "High Yield Logistics Tenant Corridor"], "DLD Escrow #98450 / Mashreq", false],
  ["HAYAT ISLAND COVE PHASE 2", "Mina Al Arab, Hayat Island", "Ras Al Khaimah", "Off-Plan", "Apartments", 1150000, "Q4 2028", "1BR & 2BR Coastal Island Suites", "60/40 Construction Linked", 18, 9.5, ["Direct Flamingo Wetland Reserve", "Wynn Al Marjan Island 12 Mins", "Private White Beach Access", "High Rental Capital Yield"], "RAK Municipality Escrow #44102", true],
  ["EXPO CITY SHURAAK TOWERS", "Expo City Dubai Central", "Dubai", "Off-Plan", "Apartments", 1450000, "Q2 2029", "1BR, 2BR & 3BR Net Zero Flats", "60/40 Construction Linked", 10, 9.2, ["Terra Sustainability Pavilion Frontage", "Smart Autonomous Shuttle Routes", "100% Pedestrianized Eco District", "Direct Dubai Metro Red Line Station"], "DLD Escrow #99104 / Emirates NBD", true],
  ["YAS NORTH BAY HARBOUR HOMES", "Yas North Marina, Yas Island", "Abu Dhabi", "Off-Plan", "Apartments", 1380000, "Q4 2028", "1BR, 2BR & 3BR Marina View Units", "60/40 (10% Down)", 16, 9.3, ["Yas Waterworld & SeaWorld 3 Mins", "Infinity Marina Edge Pool", "Direct Water Boardwalk Dining", "Short-Term Vacation License Included"], "AD DMT Escrow #47190 / FAB", false],
  ["MEYDAN WATERFRONT DISTRICT PHASE 3", "Meydan Horizon Canal", "Dubai", "Off-Plan", "Apartments", 1680000, "Q3 2028", "1BR, 2BR & 3BR Horizon Residences", "60/40 Construction Linked", 22, 8.7, ["4km Swimmable Canal Network", "Downtown Skyline Direct View", "Boardwalk Cafes & Fine Dining", "Direct Ras Al Khor Highway Flyover"], "DLD Escrow #95123 / CBD", false],
  ["GRAND POLO RETREAT PHASE 2", "Grand Polo Resort Masterplan", "Dubai", "Off-Plan", "Villas", 7200000, "Q1 2029", "4BR & 5BR Polo Field Residences", "60/40 Construction Linked", 12, 8.2, ["Polo Field Direct Frontage", "Clubhouse Stables & Equestrian Track", "Organic Farm-to-Table Dining", "Smart Private Swimming Pool"], "DLD Escrow #98104 / Emirates NBD", false],
  ["THE VALLEY VELORA TOWNHOMES", "The Valley Phase 2, Emaar", "Dubai", "Off-Plan", "Townhouses", 2250000, "Q2 2029", "3BR & 4BR Nature Townhomes", "60/40 Construction Linked", 10, 9.0, ["Flowing Dune Landscape Trails", "Golden Beach with Wave Lagoon", "Sports Hub & Rock Climbing Wall", "Al Ain Road Direct Highway Link"], "DLD Escrow #99210 / Emirates NBD", false],
  ["SOBHA VERDE JLT MASTER TOWER", "JLT Cluster H Masterplan", "Dubai", "Off-Plan", "Apartments", 1880000, "Q3 2028", "1BR, 2BR & 3BR Luxury Golf Overlook", "60/40 Construction Linked", 24, 8.6, ["Emirates Golf Club Panoramic Views", "Infinity Sky Lounge on Level 65", "Smart Home Automation", "DMCC Metro Station 5-Min Walk"], "DLD Escrow #94301 / ADCB", false],
  ["AL MAMSHA SHARJAH URBAN MASTER", "Al Mamsha Central, Sharjah", "Sharjah", "Off-Plan", "Apartments", 690000, "Q4 2028", "Studio, 1BR & 2BR Pedestrian Flats", "50/50 (1% Monthly Post-Handover)", 20, 10.0, ["100% Car-Free Underground Parking", "University City Sharjah 2 Mins", "Direct Sharjah Airport Highway", "Water Splash Parks & Retail Souk"], "Sharjah Real Estate Escrow #22101", false],
  ["RAMHAN ISLAND SIGNATURE VILLAS", "Ramhan Island, Abu Dhabi Coast", "Abu Dhabi", "Off-Plan", "Villas", 11500000, "Q2 2029", "4BR, 5BR & 6BR Natural Sea Channel Homes", "60/40 (10% Down Payment)", 12, 7.8, ["Natural Sea Channels & Mangroves", "Private Marina & Yacht Club", "Luxury Wellness Spa & Resort Hotel", "Direct Abu Dhabi Mainland Causeway"], "AD DMT Escrow #58102 / FAB", true],
  ["DUBAI CREEK HARBOUR MANGROVE SUITES", "Ras Al Khor Overlook, DCH", "Dubai", "Off-Plan", "Apartments", 1920000, "Q4 2028", "1BR, 2BR & 3BR Biophilic Units", "60/40 Construction Linked", 18, 8.6, ["Protected Flamingo Sanctuary Panorama", "Creek Marina Sunset Promenade", "Hydro-Wellness Mineral Baths", "Eco-Smart District Microgrid"], "DLD Escrow #96120 / DIB", false],
  ["TILAL AL GHAF PLAGIA RESIDENCES", "Plagia Lagoon, Tilal Al Ghaf", "Dubai", "Off-Plan", "Villas", 6800000, "Q1 2029", "4BR & 5BR Lagoonfront Homes", "60/40 Handover Linked", 14, 8.1, ["Private Sandy Beach Frontage", "Royal Grammar School Guildford Near", "Smart Home Voice Controlled Air/Light", "Private Plunge Lagoon Pool"], "DLD Escrow #97910 / FAB", false],
  ["PALM CROWN WATERFRONT TOWERS", "Palm Jumeirah Gateway Master", "Dubai", "Off-Plan", "Apartments", 4800000, "Q3 2028", "2BR, 3BR & 4BR Royal Sky Suites", "60/40 Construction Linked", 20, 7.6, ["Panoramic Palm Crescent Views", "Private Beachfront Club Membership", "Michelin Star In-Building Brasserie", "Helipad Booking Protocol"], "DLD Escrow #95211 / Emirates NBD", true]
];

const abuDhabiSovereign = [
  ["VANTAGE SAADIYAT CULTURAL SUITES", "Cultural District, Saadiyat Island", "Abu Dhabi", "Off-Plan", "Apartments", 2450000, "Q4 2028", "1BR, 2BR & 3BR Museum View Suites", "60/40 Construction Linked", 18, 8.2, ["Louvre Abu Dhabi Unobstructed Panorama", "Guggenheim Abu Dhabi Walking Distance", "Private Beach Club Pass", "AD DMT Escrow #49102 / FAB"], "AD DMT Escrow #49102 / FAB", true],
  ["YAS BAY MARINA RESIDENCES", "Yas Bay South, Yas Island", "Abu Dhabi", "Under Construction", "Apartments", 1680000, "Q2 2027", "1BR, 2BR & 3BR Marina Suites", "70/30 on Completion", 58, 8.9, ["Etihad Arena 200m Walk", "Hilton Yas Bay Dining Strip", "Infinity Marina Deck & Pool", "Short-Term Vacation Rental License"], "AD DMT Escrow #45112 / ADCB", true],
  ["MAMSHA AL SAADIYAT BEACH SUITES", "Mamsha Al Saadiyat, Saadiyat Beach", "Abu Dhabi", "Ready", "Apartments", 4100000, "Ready for Handover", "2BR, 3BR & 4BR Direct Beachfront", "100% Ready (Immediate Handover)", 100, 7.5, ["White Sand Saadiyat Beach Direct Walk", "Soul Beach Promenade Cafes", "Infinity Swimming Pool & Spa", "Private Resident Beach Loungers"], "AD DMT Title Deed Ready", true],
  ["AL REEM SKY TOWER PANORAMA", "Marina Square, Al Reem Island", "Abu Dhabi", "Ready", "Apartments", 1250000, "Ready for Handover", "1BR, 2BR & 3BR Seafront Towers", "Mortgage Ready with 8.8% Yield", 100, 9.0, ["Al Maryah Financial Freezone 3 Mins", "Reem Central Park Frontage", "Olympic Size Lap Pool & Tennis Courts", "Carrefour in Podium"], "AD DMT Certified", false],
  ["JUBAIL MANGROVE ISLAND RETREAT", "Jubail Island Eco Park", "Abu Dhabi", "Under Construction", "Villas", 5900000, "Q1 2028", "4BR & 5BR Eco Sanctuaries", "60/40 Handover Linked", 42, 8.0, ["Natural Mangrove Kayaking Trails", "Private Marina Slipway", "Clubhouse with Organic Spa", "Zero-Carbon Eco Building Materials"], "AD DMT Escrow #54110 / FAB", true],
  ["SAADIYAT GROVE SIGNATURE FLATS", "Saadiyat Grove District", "Abu Dhabi", "Under Construction", "Apartments", 1950000, "Q3 2027", "Studio, 1BR & 2BR Cultural Flats", "70/30 Construction Linked", 50, 8.6, ["Direct Underground Louvre Tunnel", "Saadiyat Grove Luxury Mall Concourse", "Rooftop Stargazing Pools", "Smart Biometric Security"], "AD DMT Escrow #51221 / ADIB", false],
  ["AL MARYAH VISTA LUXE TOWER", "Al Maryah Island Financial Freezone", "Abu Dhabi", "Ready", "Apartments", 1480000, "Ready for Handover", "1BR & 2BR Canal Facing Suites", "Ready 100% / Sovereign Financing", 100, 8.7, ["ADGM Financial Center 2-Min Walk", "The Galleria Luxury Mall Concourse", "Cleveland Clinic Abu Dhabi 3 Mins", "High Yield Financial Expat Hub"], "AD DMT Title Deed Ready", true],
  ["YAS GOLF COLLECTION SEA VIEWS", "Yas Links Golf, Yas Island", "Abu Dhabi", "Under Construction", "Apartments", 1850000, "Q4 2027", "1BR, 2BR & 3BR Golf Panorama", "60/40 Handover Linked", 48, 8.8, ["Yas Links 18-Hole Championship View", "Infinity Horizon Swimming Pool", "Fitness & Yoga Studios", "Short Term Holiday Home License"], "AD DMT Escrow #48910 / FAB", false],
  ["SAADIYAT RESERVE MANSION PLOTS", "Saadiyat Island Reserve", "Abu Dhabi", "Under Construction", "Villas", 12800000, "Q2 2028", "5BR & 6BR Dunefront Mansions", "60/40 Construction Linked", 36, 7.3, ["Direct Saadiyat Beach Coastline", "Native Botanical Wildlife Park", "Sub-Zero Gourmet Kitchen & Scullery", "Staff Quarters & Triple Car Port"], "AD DMT Escrow #52441 / ADCB", false],
  ["AL RAHA LOFTS WATERFRONT", "Al Raha Beach Canal", "Abu Dhabi", "Ready", "Apartments", 1100000, "Ready for Handover", "Studio, 1BR & 2BR Canal Lofts", "Ready Cash / 80% Mortgage", 100, 9.2, ["Al Raha Beach Boardwalk Cafes", "Rooftop Swimming Pool & Gym", "Abu Dhabi International Airport 8 Mins", "Canal Water Taxi Terminals"], "AD DMT Title Deed Issued", false],
  ["YAS PARK GATE LUXE VILLAS", "Yas Park District, Yas Island", "Abu Dhabi", "Under Construction", "Villas", 3800000, "Q1 2028", "3BR & 4BR Modern Countryside Villas", "60/40 Construction Linked", 40, 8.4, ["Yas Park Forest Playgrounds & Splash", "Ferrari World & Yas Mall 4 Mins", "Private Swimming Pool Option", "Smart Energy Management"], "AD DMT Escrow #47119 / FAB", false],
  ["REEM HILLS LUXURY SANCTUARY", "Reem Hills, Al Reem Island", "Abu Dhabi", "Under Construction", "Villas", 6800000, "Q3 2027", "4BR, 5BR & 6BR Hillside Mansions", "70/30 Handover Linked", 54, 7.9, ["Abu Dhabi's First Gated Hillside Master", "Private Forest Walking Trails", "Infinity Lagoon & Private Club", "Gated Security & Valet Desk"], "AD DMT Escrow #50112 / ADIB", true],
  ["SAADIYAT NOYA TOWNHOMES", "Yas North / Noya District", "Abu Dhabi", "Ready", "Townhouses", 2100000, "Ready for Handover", "3BR & 4BR Family Townhomes", "Ready for Move-In", 100, 8.9, ["Community Center & Waterpark", "Sports Hub & Padel Courts", "GEMS World Academy Proximity", "Yas Theme Parks 5 Mins"], "AD DMT Certified", false],
  ["AL GURM LAGOON ESTATE", "Al Gurm Marine Sanctuary", "Abu Dhabi", "Ready", "Villas", 21500000, "Ready for Handover", "5BR & 6BR Mangrove Sea Mansions", "Cash / Sovereign Bank Approval", 100, 6.8, ["Private Marina Berth & Water Jetty", "Tidal Mangrove Wildlife Channels", "Smart Biometric Security Perimeter", "Private Spa Pavilion & Sauna"], "AD DMT Title Deed Ready", false],
  ["YAS RIVA WATERFRONT CANAL VILLA", "Yas Island Riva Canal", "Abu Dhabi", "Off-Plan", "Villas", 7900000, "Q1 2029", "4BR, 5BR & 6BR Canal Mansions", "60/40 Construction Linked", 12, 8.1, ["Direct Waterway Boat Dock Option", "Etihad Arena & Bay Promenade 5 Mins", "Zero Carbon Architectural Design", "Private Glass Infinity Pool"], "AD DMT Escrow #56110 / FAB", true],
  ["WATER'S EDGE YAS CANAL FLATS", "Water's Edge, Yas Island", "Abu Dhabi", "Ready", "Apartments", 980000, "Ready for Handover", "1BR & 2BR Canal View Apartments", "Ready with 9.1% Verified ROI", 100, 9.4, ["Yas Marina Promenade Direct Access", "Olympic Length Swimming Pools", "Private Jogging & Cycling Tracks", "High Expat Vacation Rental Demand"], "AD DMT Title Deed Cleared", false],
  ["SAADIYAT BEACH GOLF RESIDENCES", "Saadiyat Beach Golf Club", "Abu Dhabi", "Ready", "Apartments", 3200000, "Ready for Handover", "2BR & 3BR Golf & Seafront Flats", "Ready for Move-In", 100, 7.9, ["Gary Player 18-Hole Course Views", "St. Regis & Park Hyatt Dining 2 Mins", "Private Residents Gym & Lap Pool", "Direct Turtle Beach Boardwalk"], "AD DMT Title Deed Ready", false],
  ["AL HADEEL AL RAHA WATER SUITES", "Al Bandar, Al Raha Beach", "Abu Dhabi", "Ready", "Apartments", 1750000, "Ready for Handover", "1BR, 2BR & 3BR Sea View Suites", "Ready 100% Cash / Mortgage", 100, 8.6, ["Al Bandar Marina Berth Access", "Waterfront Promenade Restaurants", "Infinity Edge Heated Swimming Pool", "Abu Dhabi Corniche 15 Mins"], "AD DMT Title Deed Ready", false],
  ["JUBAIL SOUK WATER RESIDENCES", "Souk Al Jubail, Jubail Island", "Abu Dhabi", "Off-Plan", "Apartments", 1950000, "Q4 2028", "1BR, 2BR & 3BR Boardwalk Suites", "60/40 Construction Linked", 16, 8.5, ["Boardwalk Cafes & Organic Delis", "Mangrove Kayak Launch Ramp", "Rooftop Horizon Lap Pool", "Zero Emission Community Shuttles"], "AD DMT Escrow #55120 / ADCB", false],
  ["YAS FLAMINGO BAY RESIDENCES", "Yas South Shoreline", "Abu Dhabi", "Off-Plan", "Apartments", 1520000, "Q3 2028", "1BR, 2BR & 3BR Resort Suites", "60/40 (10% Down Payment)", 20, 9.1, ["Ferrari World & SeaWorld Proximity", "Resort Lagoons & Sun Cabanas", "Private Padel & Tennis Academy", "Full Turnkey Furniture Packages Available"], "AD DMT Escrow #49811 / FAB", false],
  ["SHAMS MEERA TOWERS", "Shams Abu Dhabi, Al Reem Island", "Abu Dhabi", "Ready", "Apartments", 1050000, "Ready for Handover", "1BR & 2BR High-Rise Flats", "Immediate Handover", 100, 9.3, ["Shams Central Park Overlook", "Reem Mall & Snow Abu Dhabi 5 Mins", "Olympic Swimming Pool & Gym", "High Occupancy Expat Rental Hub"], "AD DMT Title Deed Ready", false],
  ["RAMHAN SEAVIEW APEX VILLA", "Ramhan Island Shoreline", "Abu Dhabi", "Off-Plan", "Villas", 14500000, "Q2 2029", "5BR & 6BR Sovereign Palaces", "60/40 (10% Down)", 10, 7.6, ["Unobstructed Open Arabian Gulf Front", "Private Marina Mooring Slip", "Dedicated Wellness Thermal Spa", "Private Chauffeur & Butler Service"], "AD DMT Escrow #59104 / FAB", true],
  ["AL MARYAH CENTRAL METROPOLIS", "Al Maryah North Financial", "Abu Dhabi", "Under Construction", "Apartments", 1650000, "Q2 2028", "1BR & 2BR Corporate Suites", "70/30 on Completion", 42, 8.8, ["Direct Footbridge to ADGM Courts", "Galleria Mall Michelin Dining Concourse", "High Speed Fiber Infrastructure", "Executive Business Lounge"], "AD DMT Escrow #51440 / ADIB", false],
  ["SAADIYAT MARINA HORIZON SUITES", "Saadiyat Marina Phase 2", "Abu Dhabi", "Off-Plan", "Apartments", 2700000, "Q1 2029", "2BR & 3BR Marina Residences", "60/40 Construction Linked", 14, 8.0, ["Louvre Abu Dhabi Skyline Vista", "Private Marina Slipway", "Technogym Wellness Club", "24/7 Diplomatic Concierge"], "AD DMT Escrow #57122 / FAB", false],
  ["YAS LIVING PARK RETREAT", "Yas East Parklands", "Abu Dhabi", "Under Construction", "Townhouses", 2450000, "Q4 2027", "3BR & 4BR Modern Family Homes", "60/40 Construction Linked", 52, 8.7, ["Yas Acres Golf Course Proximity", "Lush Linear Parkland Frontage", "Multiple Swimming Pools & Sports Courts", "Direct E11 Dubai Highway Access"], "AD DMT Escrow #48110 / ADCB", false],
  ["AL REEM WATERSQUARE TOWERS", "City of Lights, Al Reem Island", "Abu Dhabi", "Ready", "Apartments", 1180000, "Ready for Handover", "1BR & 2BR Water Promenade Flats", "Ready Cash / Mortgage", 100, 9.2, ["Marina Boardwalk Promenade", "Al Maryah Bridge 1-Min Drive", "Gym, Sauna & Steam Rooms", "High Yield Professional Tenant Base"], "AD DMT Title Deed Cleared", false],
  ["SAADIYAT LAGOONS DUNE VILLA", "Saadiyat Eco Dunes", "Abu Dhabi", "Under Construction", "Villas", 8100000, "Q2 2028", "4BR & 5BR Biophilic Eco Mansions", "60/40 Milestone Linked", 38, 7.8, ["Protected Wilderness Reserve Views", "Private Dune Infinity Swimming Pool", "Zero Energy Solar Microgrid", "Cranleigh Abu Dhabi 5 Mins"], "AD DMT Escrow #53881 / FAB", false],
  ["AL SEEF CORNICHE RETREAT", "Al Seef District, Abu Dhabi", "Abu Dhabi", "Ready", "Apartments", 1850000, "Ready for Handover", "2BR & 3BR Luxury Corniche Suites", "Ready 100% Cash / Mortgage", 100, 8.5, ["Abu Dhabi Corniche Beach 3 Mins", "Emirates Palace Vista", "Rooftop Horizon Pool & Spa", "Diplomatic Gated Compound"], "AD DMT Title Deed Ready", false]
];

const commercialGradeA = [
  ["VANTAGE APEX COMMERCIAL TOWER", "DIFC Gate District Gateway", "Dubai", "Off-Plan", "Commercial", 4500000, "Q4 2028", "Grade-A Corporate Headquarters & Offices", "60/40 Construction Linked", 16, 9.0, ["DIFC Financial Freezone Jurisdiction", "LEED Platinum Certified Architecture", "Executive Helipad & Boardrooms", "High-Speed Elevators with Destination Dispatch"], "DLD Escrow #99602 / FAB", true],
  ["BUSINESS BAY FINTECH HUB TOWER", "Business Bay Financial Boulevard", "Dubai", "Under Construction", "Commercial", 2800000, "Q2 2027", "Boutique Serviced Tech Offices & Floors", "70/30 Handover Linked", 62, 9.8, ["Tier-3 Data Center Ready Infrastructure", "Business Bay Metro 2-Min Walk", "Rooftop Executive Networking Lounge", "Smart AI Visitor Management System"], "DLD Escrow #83110 / Emirates NBD", true],
  ["DMCC METROPOLIS COMMODITIES TOWER", "Uptown Dubai, DMCC District", "Dubai", "Under Construction", "Commercial", 3600000, "Q3 2027", "Grade-A Freezone Headquarters", "60/40 Milestone Linked", 50, 9.4, ["DMCC Freezone 0% Corporate Tax License", "Direct Uptown Plaza Concourse", "Auditorium & Conference Suites", "24/7 Secure Vault Facilities"], "DLD Escrow #87201 / Mashreq", true],
  ["DUBAI INTERNET CITY TECH PARK", "Dubai Internet City Phase 2", "Dubai", "Ready", "Commercial", 5200000, "Ready for Handover", "Full Floor Tech Enterprise Headquarters", "Ready 100% / Corporate Mortgage", 100, 8.9, ["TECOM Freezone License", "Fortune 500 Corporate Neighborhood", "High-Speed 10Gbps Redundant Dark Fiber", "Podium Food & Beverage Courtyard"], "DLD Title Deed Ready", false],
  ["AL MARYAH CAPITAL TOWER", "ADGM Square, Al Maryah Island", "Abu Dhabi", "Under Construction", "Commercial", 4900000, "Q1 2028", "Sovereign & Hedge Fund Office Suites", "60/40 Construction Linked", 44, 8.8, ["ADGM Financial Freezone Common Law", "Direct Bridge to Galleria Luxury Mall", "State-of-the-Art Bloomberg Trading Hubs", "24/7 Diplomatic Grade Security"], "AD DMT Escrow #51901 / FAB", true],
  ["DUBAI SCIENCE PARK LAB & HQ TOWER", "Dubai Science Park, Barsha South", "Dubai", "Ready", "Commercial", 3100000, "Ready for Handover", "Biopharma Certified Labs & Offices", "Ready Cash / Bank Financing", 100, 9.6, ["Specialized Wet & Dry Lab Infrastructure", "Dubai Science Park Freezone License", "Solar Energy Powered Microgrid", "Ample Multi-Level Parking"], "DLD Title Deed Cleared", false],
  ["DOWNTOWN SKY EXECUTIVE TOWER", "Downtown Dubai Boulevard", "Dubai", "Under Construction", "Commercial", 6400000, "Q4 2027", "Burj Facing Corporate Headquarters", "70/30 on Completion", 55, 8.7, ["Unobstructed Burj Khalifa Views", "VIP Valet Parking for 200 Cars", "Private Boardrooms & Executive Terraces", "Direct Dubai Mall Air-Conditioned Tunnel"], "DLD Escrow #85910 / ADCB", false],
  ["EXPO CITY COMMERCIAL INNOVATION HUB", "Expo City Dubai Central Plaza", "Dubai", "Off-Plan", "Commercial", 2950000, "Q1 2029", "Net Zero Grade-A Tech & AI Offices", "60/40 Construction Linked", 14, 9.5, ["Expo City Dubai Freezone Benefits", "100% Renewable Energy Powered", "Direct Metro Red Line Link", "Collaborative Innovation Sandbox"], "DLD Escrow #98119 / Emirates NBD", true],
  ["DUBAI SILICON PARK COMMERCE HQ", "Dubai Silicon Oasis High-Tech Hub", "Dubai", "Ready", "Commercial", 2400000, "Ready for Handover", "Tech Startup & Scaler HQ Suites", "Ready with 9.2% Proven Corporate Yield", 100, 9.7, ["DSO Freezone 100% Foreign Ownership", "Electric Autonomous Shuttle Fleet", "Smart Conference Rooms & Podcast Pods", "Sub-station Power Redundancy"], "DLD Title Deed Ready", false],
  ["JAFZA LOGISTICS COMMERCIAL TOWER", "JAFZA South Gateway, Jebel Ali", "Dubai", "Ready", "Commercial", 3800000, "Ready for Handover", "Maritime & Logistics Enterprise Suites", "Ready 100% Cash / Financing", 100, 10.1, ["Direct Jebel Ali Sea Port & Air Link", "JAFZA Freezone Customs Integration", "Custom Clearance Priority Desks", "Heavy Vehicle Dedicated Access"], "DLD Title Deed Issued", false],
  ["AL REEM FINANCIAL TOWER", "Shams Financial Center, Al Reem", "Abu Dhabi", "Under Construction", "Commercial", 2600000, "Q3 2028", "Corporate Law & Wealth Management HQ", "60/40 Handover Linked", 36, 9.2, ["ADGM Freezone Satellite Connectivity", "Canal Promenade Executive Dining", "High Speed Elevators with AI Dispatch", "Secure Server Rooms on Each Floor"], "AD DMT Escrow #54119 / ADIB", false],
  ["MEYDAN RACETRACK COMMERCE PLAZA", "Meydan Horizon Avenue", "Dubai", "Off-Plan", "Commercial", 3400000, "Q4 2028", "Equestrian & Luxury Brand Showroom Offices", "60/40 Construction Linked", 18, 9.1, ["Meydan Grandstand Panoramic Views", "Double Height Luxury Showroom Facades", "Direct Al Khail Road Highway Access", "VIP Executive Helipad Protocol"], "DLD Escrow #96120 / CBD", false],
  ["DUBAI MARITIME HUB TOWER", "Dubai Maritime City Commercial", "Dubai", "Under Construction", "Commercial", 2900000, "Q2 2028", "Ship Management & Offshore Energy Offices", "60/40 Construction Linked", 40, 9.3, ["Direct Arabian Gulf Drydocks Overlook", "Maritime City Freezone License", "Private Yacht Mooring for Executives", "Cruise Terminal 5-Min Drive"], "DLD Escrow #91440 / Emirates Islamic", false],
  ["TECOM MEDIA PLAZA COMMERCE", "Dubai Media City Sector 4", "Dubai", "Ready", "Commercial", 4200000, "Ready for Handover", "Broadcasting & Global Media HQs", "Ready 100% Cash / Mortgage", 100, 8.8, ["TECOM Media Freezone License", "Studio Sound Stages & Green Screens", "Media City Amphitheater Frontage", "Dubai Tram Direct Connection"], "DLD Title Deed Ready", false],
  ["AL MAQTA BRIDGE COMMERCE TOWER", "Bain Al Jessrain, Abu Dhabi", "Abu Dhabi", "Ready", "Commercial", 3500000, "Ready for Handover", "Embassy & Diplomatic Corporate Suites", "Ready for Move-In", 100, 8.6, ["Grand Mosque Panoramic Panorama", "Ultra High Security Infrastructure", "Diplomatic Private Car Parking", "Al Maqta Water Canal Boardwalk"], "AD DMT Title Deed Ready", false],
  ["DUBAI AIRPORT FREEZONE APEX", "DAFZA Central Plaza", "Dubai", "Under Construction", "Commercial", 4100000, "Q1 2028", "Aviation & Cargo Logistics HQ", "70/30 Construction Linked", 48, 9.4, ["Direct DAFZA Customs Fast-Track", "DXB Terminal 2 Runway Frontage", "Freezone 100% Tax Exemption", "Automated Cargo Handling Integration"], "DLD Escrow #88910 / DIB", false],
  ["BUSINESS BAY CANAL COMMERCE TOWER", "Business Bay Marasi Drive", "Dubai", "Off-Plan", "Commercial", 3100000, "Q3 2028", "Boutique Executive Law & Finance Suites", "60/40 (10% Down Payment)", 20, 9.3, ["Canal Promenade Frontage", "Rooftop Infinity Business Lounge", "Smart AI Automated Access", "Dubai Mall & Metro 5 Mins"], "DLD Escrow #95410 / FAB", false],
  ["SHARJAH INNOVATION TECH TOWER", "Sharjah Research & Tech Park", "Sharjah", "Under Construction", "Commercial", 1850000, "Q4 2027", "SRTI Freezone Tech Startup Floors", "60/40 Construction Linked", 55, 10.4, ["Sharjah University City Hub", "SRTI Freezone License 0% Corporate Tax", "3D Printing & AI Sandbox Facilities", "Direct E88 Airport Highway Access"], "SRTI Freezone Escrow #1109", false],
  ["DUBAI SOUTH LOGISTICS PARK HQ", "Logistics District, Dubai South", "Dubai", "Ready", "Commercial", 4800000, "Ready for Handover", "Supply Chain Enterprise Warehouse & Offices", "Ready Cash / Financing", 100, 9.9, ["Direct Bonded Sea-Air Corridor to Jebel Ali", "Al Maktoum Airport Airside Access", "Heavy Duty Fleet Loading Docks", "Solar Powered Cold Storage Ready"], "DLD Title Deed Ready", false],
  ["DIFC SOUTH GATE COMMERCE SUITES", "DIFC Gate Village South", "Dubai", "Off-Plan", "Commercial", 5800000, "Q2 2029", "Private Equity & Family Office Suites", "60/40 Construction Linked", 12, 8.5, ["DIFC Law & Independent Courts", "Gate Village Michelin Art Restaurants", "High-End Art Gallery Concierge", "Valet Parking for 350 Cars"], "DLD Escrow #98990 / Emirates NBD", true],
  ["AL BARSHA FINANCIAL CENTER", "Al Barsha Heights (TECOM)", "Dubai", "Ready", "Commercial", 2650000, "Ready for Handover", "Multi-Tenant Corporate Office Suites", "Ready 100% Cash / Mortgage", 100, 9.5, ["Dubai Internet City Metro 3-Min Walk", "High Occupancy Corporate Tenants", "Full Floor Floorplans Available", "Ample Multi-Level Basement Parking"], "DLD Title Deed Cleared", false],
  ["KHALIFA INDUSTRIAL ZONE (KEZAD) HQ", "KEZAD Taweelah, Abu Dhabi", "Abu Dhabi", "Under Construction", "Commercial", 3900000, "Q2 2028", "Manufacturing & Heavy Industrial HQs", "60/40 Construction Linked", 40, 9.7, ["Khalifa Deep Sea Port Direct Link", "KEZAD Special Economic Zone License", "Gas & High-Voltage Heavy Power Ready", "Rail Freight Terminal Integration"], "AD DMT Escrow #54901 / FAB", false],
  ["BARSHA SOUTH MEDICAL COMMERCE", "Dubai Science Park Medical Corridor", "Dubai", "Under Construction", "Commercial", 3300000, "Q1 2028", "Specialist Medical & Wellness Suites", "70/30 on Completion", 46, 9.2, ["DHA Approved Healthcare Facility Design", "Patient Drop-Off Valet Portico", "Specialized Medical Waste Systems", "Ample Underground Patient Parking"], "DLD Escrow #89112 / CBD", false],
  ["PORT RASHID COMMERCE HAVEN", "Mina Rashid Maritime Center", "Dubai", "Off-Plan", "Commercial", 3700000, "Q4 2028", "Superyacht Management & Brokerage HQ", "60/40 Construction Linked", 15, 8.9, ["Marina Mooring View from Offices", "Historic Queen Elizabeth 2 Frontage", "Direct Jumeirah Coastal Highway", "Executive Cigar & Boardroom Lounge"], "DLD Escrow #96811 / Emirates NBD", false],
  ["CITY WALK INNOVATION STUDIOS", "City Walk Creative District", "Dubai", "Under Construction", "Commercial", 4600000, "Q3 2027", "Fashion, Design & Creative Agency Lofts", "60/40 Milestone Linked", 58, 8.8, ["Double Height Industrial Lofts", "City Walk Dining Piazza Frontage", "Smart Acoustic Insulation", "24/7 Creative Studio Access"], "DLD Escrow #86109 / ADCB", false],
  ["AL MARYAH SATELLITE TECH COMMERCE", "Al Maryah North Freezone", "Abu Dhabi", "Off-Plan", "Commercial", 4300000, "Q1 2029", "Fintech & Blockchain Enterprise Tower", "60/40 Construction Linked", 10, 9.1, ["ADGM Regulatory Sandbox Ready", "High-Performance Quantum Computing Cooling", "Rooftop Helipad & Executive Club", "Direct Galleria Walkway"], "AD DMT Escrow #59110 / FAB", false]
];

const ecoSmartNetZero = [
  ["VANTAGE BIOPHILIC SOLAR APEX", "Sustainable City Masterplan, Dubailand", "Dubai", "Off-Plan", "Apartments", 1450000, "Q4 2028", "1BR, 2BR & 3BR Net-Zero Solar Residences", "60/40 Construction Linked", 18, 9.2, ["100% Solar Powered Rooftop Energy", "Zero Service Charges via Renewable Feed-in", "Bio-Dome Urban Vegetable Farming", "Autonomous Electric Vehicle Shuttles"], "DLD Escrow #99710 / Emirates NBD", true],
  ["EXPO VALLEY BIODOME RESIDENCES", "Expo Valley, Expo City Dubai", "Dubai", "Under Construction", "Townhouses", 3800000, "Q2 2028", "3BR & 4BR Eco-Certified Townhouses", "60/40 Handover Linked", 40, 8.8, ["Protected Gazelle Wildlife Corridor", "Zero-Carbon Concrete Construction", "Greywater Recycling Irrigation", "Direct Dubai Metro Blue/Red Line Link"], "DLD Escrow #92110 / Emirates NBD", true],
  ["MASDAR SOLAR ECO RESIDENCES", "Masdar City Central, Abu Dhabi", "Abu Dhabi", "Ready", "Apartments", 980000, "Ready for Handover", "Studio, 1BR & 2BR Passive Energy Flats", "Ready 100% / Masdar Green Mortgage", 100, 9.7, ["Masdar City Clean Tech Freezone", "Passive Solar Windtower Architecture", "Personal Rapid Transit (PRT) Pods", "IRENA Global HQ Neighborhood"], "AD DMT Title Deed Ready", true],
  ["SHARJAH SUSTAINABLE CITY VILLA", "Sharjah Sustainable City", "Sharjah", "Ready", "Villas", 2400000, "Ready for Handover", "3BR & 4BR Zero-Energy Solar Villas", "Ready with 0% Energy Bills", 100, 9.5, ["100% Rooftop Solar PV Panels", "Indoor Vertical Farming Greenhouses", "Recycled Waste Management System", "Free Electric Buggy with Every Villa"], "Sharjah Real Estate Title Ready", true],
  ["SOBHA BIOPHILIC WATERFRONT RETREAT", "Sobha Hartland II Sanctuary", "Dubai", "Under Construction", "Apartments", 1750000, "Q3 2027", "1BR, 2BR & 3BR Forest Facing Flats", "70/30 Handover Linked", 56, 8.7, ["30% Tree Canopy Urban Forest", "Ras Al Khor Flamingo Sanctuary Panorama", "Air Filtration with HEPA Grade Purification", "Rainwater Harvesting Cascades"], "DLD Escrow #86102 / ADCB", true],
  ["TILAL AL GHAF BIOPHILIC HAVEN", "Harmony 3, Tilal Al Ghaf", "Dubai", "Under Construction", "Villas", 5800000, "Q1 2028", "4BR & 5BR Garden Pod Eco Villas", "60/40 Construction Linked", 45, 8.2, ["BREEAM Excellent Certified Design", "Natural Lagoon Al Ghaf Filtration", "Organic Herb & Citrus Gardens", "Smart Geothermal Cooling"], "DLD Escrow #89110 / FAB", false],
  ["MASDAR CENTRAL PARK SUITES", "Masdar Green Boulevard", "Abu Dhabi", "Off-Plan", "Apartments", 1250000, "Q3 2028", "1BR, 2BR & 3BR Carbon-Neutral Flats", "60/40 (10% Down Payment)", 20, 9.4, ["Masdar Central Park Frontage", "Smart Smart Thermostat Integration", "Shaded Pedestrian Walkways", "Abu Dhabi Airport 5 Mins"], "AD DMT Escrow #49112 / First Abu Dhabi Bank", false],
  ["AL BARARI BIO-SANCTUARY SUITES", "The Nest, Al Barari", "Dubai", "Ready", "Villas", 12500000, "Ready for Handover", "4BR & 5BR Botanical Sanctuary Villas", "Ready Cash / Bank Mortgage", 100, 7.6, ["80% Gated Botanical Canopy", "Freshwater Natural Streams", "The Farm Organic Restaurant Onsite", "Heart & Soul Holistic Wellness Spa"], "DLD Title Deed Ready", true],
  ["EXPO RESIDENCES GREEN HORIZON", "Expo City Dubai South Edge", "Dubai", "Off-Plan", "Apartments", 1380000, "Q4 2028", "1BR, 2BR & 3BR LEED Gold Apartments", "60/40 Construction Linked", 16, 9.1, ["LEED Gold Certified Efficiency", "100% Greywater Irrigation", "Smart Smart Grid Metering", "Terra Pavilion Walkway"], "DLD Escrow #96881 / Emirates NBD", false],
  ["JUBAIL ECO-LAGOON MANSIONS", "Jubail Island Sanctuary Shore", "Abu Dhabi", "Under Construction", "Villas", 8800000, "Q2 2028", "5BR Mangrove Nature Mansions", "60/40 Construction Linked", 35, 7.9, ["Protected Mangrove Reserve Border", "Solar Powered Underfloor Cooling", "Zero Chemical Saltwater Pool", "Private Electric Yacht Berth"], "AD DMT Escrow #53119 / FAB", false],
  ["THE VALLEY GREEN MEADOW HOMES", "The Valley Phase 2, Emaar", "Dubai", "Off-Plan", "Townhouses", 2050000, "Q1 2029", "3BR & 4BR Solar Ready Townhouses", "60/40 Construction Linked", 12, 9.0, ["Naturally Shaded Sand Dune Trails", "Community Organic Farm & Compost Hub", "Solar Street Lighting", "Golden Beach Wave Pool Access"], "DLD Escrow #98410 / Emirates NBD", false],
  ["DAMAC RIVERSIDE ECO TOWNHOMES", "DAMAC Riverside Green Quarter", "Dubai", "Off-Plan", "Townhouses", 2100000, "Q3 2028", "4BR Biophilic Stream Townhouses", "70/30 Handover Linked", 22, 9.0, ["Hydroponic Growing Pods", "Water Filtration Bio-Swales", "Essential Oil Herb Gardens", "Aquatic Aerobics Lagoon"], "DLD Escrow #95112 / DIB", false],
  ["MASDAR OASIS SMART FLATS", "Masdar Tech Corridor", "Abu Dhabi", "Under Construction", "Apartments", 1100000, "Q4 2027", "Studio, 1BR & 2BR Smart Eco Units", "70/30 on Handover", 50, 9.5, ["Automated Energy Optimization", "PRT Autonomous Station On-Site", "Rooftop Green Garden & Solar Canopy", "Zero Single-Use Plastic Community"], "AD DMT Escrow #47119 / ADCB", false],
  ["DUBAI HILLS BIOPHILIC GARDENS", "Park Field, Dubai Hills Estate", "Dubai", "Under Construction", "Apartments", 1820000, "Q2 2028", "1BR, 2BR & 3BR Park Facing Flats", "60/40 Construction Linked", 38, 8.6, ["Dubai Hills Park Direct Greenery", "Smart Low-E Solar Glazing", "Recycled Rainwater Gardens", "Electric Car Fast Charge Superhub"], "DLD Escrow #91224 / Emirates NBD", false],
  ["SHARJAH SUSTAINABLE DUPLEX HOMES", "Sharjah Sustainable City Phase 3", "Sharjah", "Under Construction", "Townhouses", 1950000, "Q1 2028", "3BR & 4BR Solar Integrated Homes", "60/40 Handover Linked", 44, 9.6, ["Zero Net Energy Architecture", "Community Solar Plant Dividends", "Indoor Farming Greenhouse Allocation", "100% Wastewater Treated for Parks"], "Sharjah Real Estate Escrow #33012", false],
  ["RAMHAN BIOPHILIC ISLAND PALACE", "Ramhan Island Eco Frond", "Abu Dhabi", "Off-Plan", "Villas", 16800000, "Q2 2029", "5BR & 6BR Coral Coast Mansions", "60/40 (10% Down Payment)", 10, 7.5, ["Natural Sea Channel Living", "Solar Geothermal Heat Pumps", "Private Electric Yacht Dock", "Certified Coral Reef Restoration Site"], "AD DMT Escrow #59910 / FAB", true],
  ["SAADIYAT WILDERNESS ECO RESERVE", "Saadiyat Cultural Eco Border", "Abu Dhabi", "Off-Plan", "Villas", 9200000, "Q4 2028", "4BR & 5BR Sustainable Stone Mansions", "60/40 Construction Linked", 16, 7.8, ["Native Ghaf Tree Canopy Living", "Zero-Carbon Rammed Earth & Local Stone", "Smart High-Efficiency Heat Recovery", "Saadiyat Cultural Museums 3 Mins"], "AD DMT Escrow #56102 / ADIB", false],
  ["EXPO CITY SKY RESIDENCES ECO", "Expo City Plaza East", "Dubai", "Under Construction", "Apartments", 1580000, "Q1 2028", "1BR, 2BR & 3BR Smart Energy Flats", "70/30 Handover Linked", 46, 9.1, ["Al Wasl Dome Direct Overlook", "District Cooling with 50% Lower Energy", "Rooftop Biophilic Garden & Yoga Pods", "Direct Metro Station"], "DLD Escrow #88224 / Emirates NBD", false],
  ["DUBAI SOUTH SOLAR HEIGHTS", "Residential City, Dubai South", "Dubai", "Off-Plan", "Apartments", 760000, "Q3 2028", "Studio & 1BR Smart Green Units", "50/50 Post-Handover (3-Years)", 18, 10.2, ["Solar Rooftop Power Microgrid", "Smart Low-Flow Water Fixtures", "Expo City & Al Maktoum Airport 8 Mins", "Linear Park Jogging Tracks"], "DLD Escrow #97224 / CBD", false],
  ["TILAL AL GHAF SERENITY RETREAT", "Serenity Mansions, Tilal Al Ghaf", "Dubai", "Under Construction", "Villas", 17500000, "Q3 2027", "5BR & 6BR Custom Eco Luxury Mansions", "70/30 Milestone Linked", 52, 7.4, ["Lagoon Al Ghaf Crystal Waters", "Net Zero Energy Building Envelope", "Private Underground Spa & Hamam", "Smart Air Quality Monitoring in Every Room"], "DLD Escrow #87110 / Mashreq", true],
  ["MASDAR GREEN PLAZA RESIDENCES", "Masdar Innovation Way", "Abu Dhabi", "Off-Plan", "Apartments", 1190000, "Q2 2029", "1BR & 2BR Carbon Neutral Suites", "60/40 Construction Linked", 12, 9.3, ["Shaded Urban Canopy & Wind Catcher", "Smart App Controlled EV Buggy Fleet", "Zero Waste to Landfill Policy", "Abu Dhabi Downtown 20 Mins"], "AD DMT Escrow #58110 / FAB", false],
  ["AL BARARI OASIS WATER SUITES", "Ashjar, Al Barari", "Dubai", "Ready", "Apartments", 2850000, "Ready for Handover", "1BR, 2BR & 3BR Forest Tree Canopy Flats", "Ready for Move-In / Mortgage", 100, 8.4, ["Floor to Ceiling Forest Views", "Natural Saltwater Lagoon Pool", "Gourmet Organic Dining 2-Min Walk", "Private Underground 2 Parking Bays"], "DLD Title Deed Ready", false],
  ["SUSTAINABLE OASIS TOWNHOUSES", "Dubailand Eco Hub", "Dubai", "Off-Plan", "Townhouses", 2200000, "Q4 2028", "3BR & 4BR Solar Powered Townhomes", "60/40 Construction Linked", 15, 9.2, ["Zero Electricity Bills via Rooftop PV", "Horse Stables & Urban Animal Farm", "Dedicated Cycling Tracks to Al Qudra", "Biodiversity Botanical Domes"], "DLD Escrow #96110 / Emirates NBD", false],
  ["RAMHAN LAGOON SANCTUARY MANSION", "Ramhan Island North Lagoon", "Abu Dhabi", "Off-Plan", "Villas", 13200000, "Q1 2029", "4BR & 5BR Marine Reserve Mansions", "60/40 (10% Down Payment)", 12, 7.7, ["Direct Natural Dolphin Waterway Views", "Solar Thermal Swimming Pool Heating", "Eco-Engineered Timber & Stone", "Abu Dhabi Cultural District 15 Mins"], "AD DMT Escrow #58990 / FAB", false]
];

const categoryList = [
  { id: "waterfront", name: "Waterfront Sky Residences", count: waterfront.length, data: waterfront, sector: "Waterfront Living" },
  { id: "ultra-luxury", name: "Ultra-Luxury Branded Mansions & Penthouses", count: ultraLuxury.length, data: ultraLuxury, sector: "High-Net-Worth Estates" },
  { id: "golf-villas", name: "Masterplan Golf & Park Villa Estates", count: golfAndVillas.length, data: golfAndVillas, sector: "Gated Communities" },
  { id: "urban-high-yield", name: "High-Yield Urban Investment Towers", count: urbanHighYield.length, data: urbanHighYield, sector: "Capital Yield & ROI" },
  { id: "offplan-masterplans", name: "Off-Plan Mega Master Community Phases", count: masterCommunityOffPlan.length, data: masterCommunityOffPlan, sector: "New Masterplans" },
  { id: "abu-dhabi-sovereign", name: "Abu Dhabi Capital Sovereign Residences", count: abuDhabiSovereign.length, data: abuDhabiSovereign, sector: "Capital Asset Class" },
  { id: "commercial-grade-a", name: "Grade-A Commercial & Serviced Tech Towers", count: commercialGradeA.length, data: commercialGradeA, sector: "Commercial & DIFC/ADGM" },
  { id: "eco-smart-netzero", name: "Eco-Smart & Net-Zero Green Living Estates", count: ecoSmartNetZero.length, data: ecoSmartNetZero, sector: "Sustainability & Solar" }
];

const images = [
  "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1582407947304-fd86f028f716?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1200&q=80"
];

let allDevelopments = [];
let globalIndex = 1;

categoryList.forEach(cat => {
  cat.data.forEach((item, idx) => {
    const id = `vtg-${globalIndex.toString().padStart(3, '0')}`;
    const [name, location, city, status, propertyType, startingPriceAed, handover, unitTypes, paymentPlan, completionPct, roiProjected, amenities, escrowCert, isFeatured] = item;
    
    // Derived down payment
    let downPaymentPct = 10;
    if (paymentPlan.includes("20% Down")) downPaymentPct = 20;
    if (paymentPlan.includes("10% Down")) downPaymentPct = 10;
    if (paymentPlan.includes("100%")) downPaymentPct = 100;
    if (paymentPlan.includes("50/50")) downPaymentPct = 20;
    if (paymentPlan.includes("70/30")) downPaymentPct = 20;

    const downPaymentAed = Math.round((startingPriceAed * downPaymentPct) / 100);
    const dldFeeAed = Math.round(startingPriceAed * 0.04);
    const oqoodAdminAed = 5250;
    const estRentalAnnualAed = Math.round((startingPriceAed * (roiProjected / 100)));

    allDevelopments.push({
      id,
      code: `VTG-${String(100 + globalIndex)}`,
      name,
      category: cat.id,
      categoryName: cat.name,
      sector: cat.sector,
      location,
      city,
      status,
      propertyType,
      startingPriceAed,
      downPaymentAed,
      downPaymentPct,
      dldFeeAed,
      oqoodAdminAed,
      estRentalAnnualAed,
      handover,
      unitTypes,
      paymentPlan,
      completionPct,
      roiProjected,
      amenities,
      escrowCert,
      isFeatured,
      image: images[(globalIndex - 1) % images.length],
      brochureSizeMb: (2.4 + (globalIndex % 5) * 0.8).toFixed(1),
      dldPermitNo: `DLD-PERMIT-${800000 + globalIndex * 17}`,
      architect: "Vantage Global Architectural Studio & Foster Partners Associates",
      coordinates: city === "Abu Dhabi" ? "24.4539° N, 54.3773° E" : (city === "Sharjah" ? "25.3573° N, 55.4033° E" : (city === "Ras Al Khaimah" ? "25.6741° N, 55.7836° E" : "25.2048° N, 55.2708° E")),
      tags: [city, status, propertyType, `${roiProjected}% ROI`, `${completionPct}% Built`]
    });

    globalIndex++;
  });
});

console.log(`Generated ${allDevelopments.length} Vantage developments across ${categoryList.length} categories.`);

const fileContent = `// Auto-generated Vantage Developments Master Catalog
// Total Verified Developments & Property Releases: ${allDevelopments.length}

export interface VantageDevelopment {
  id: string;
  code: string;
  name: string;
  category: string;
  categoryName: string;
  sector: string;
  location: string;
  city: "Dubai" | "Abu Dhabi" | "Sharjah" | "Ras Al Khaimah";
  status: "Off-Plan" | "Under Construction" | "Ready";
  propertyType: "Apartments" | "Penthouses" | "Villas" | "Townhouses" | "Commercial";
  startingPriceAed: number;
  downPaymentAed: number;
  downPaymentPct: number;
  dldFeeAed: number;
  oqoodAdminAed: number;
  estRentalAnnualAed: number;
  handover: string;
  unitTypes: string;
  paymentPlan: string;
  completionPct: number;
  roiProjected: number;
  amenities: string[];
  escrowCert: string;
  isFeatured: boolean;
  image: string;
  brochureSizeMb: string;
  dldPermitNo: string;
  architect: string;
  coordinates: string;
  tags: string[];
}

export interface VantageCategoryMeta {
  id: string;
  name: string;
  count: number;
  sector: string;
}

export const VANTAGE_CATEGORIES: VantageCategoryMeta[] = ${JSON.stringify(categoryList.map(c => ({ id: c.id, name: c.name, count: c.count, sector: c.sector })), null, 2)};

export const VANTAGE_CATALOG: VantageDevelopment[] = ${JSON.stringify(allDevelopments, null, 2)};

export const VANTAGE_CATALOG_STATS = {
  totalDevelopments: ${allDevelopments.length},
  totalReady: ${allDevelopments.filter(d => d.status === "Ready").length},
  totalUnderConstruction: ${allDevelopments.filter(d => d.status === "Under Construction").length},
  totalOffPlan: ${allDevelopments.filter(d => d.status === "Off-Plan").length},
  avgRoi: 8.4,
  cities: ["Dubai", "Abu Dhabi", "Sharjah", "Ras Al Khaimah"],
  propertyTypes: ["Apartments", "Penthouses", "Villas", "Townhouses", "Commercial"],
  totalGrossGdvAed: "AED 34.8 Billion"
};
`;

fs.writeFileSync(targetPath, fileContent, 'utf8');
console.log('Successfully wrote catalog to:', targetPath);
